# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.in_app_purchase_v2_relationships_iap_price_schedule import InAppPurchaseV2RelationshipsIapPriceSchedule

class TestInAppPurchaseV2RelationshipsIapPriceSchedule(unittest.TestCase):
    """InAppPurchaseV2RelationshipsIapPriceSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InAppPurchaseV2RelationshipsIapPriceSchedule:
        """Test InAppPurchaseV2RelationshipsIapPriceSchedule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InAppPurchaseV2RelationshipsIapPriceSchedule`
        """
        model = InAppPurchaseV2RelationshipsIapPriceSchedule()
        if include_optional:
            return InAppPurchaseV2RelationshipsIapPriceSchedule(
                links = openapi_client.models.relationship_links.RelationshipLinks(
                    self = '', 
                    related = '', ),
                data = openapi_client.models.in_app_purchase_v2_relationships_iap_price_schedule_data.InAppPurchaseV2_relationships_iapPriceSchedule_data(
                    type = 'inAppPurchasePriceSchedules', 
                    id = '', )
            )
        else:
            return InAppPurchaseV2RelationshipsIapPriceSchedule(
        )
        """

    def testInAppPurchaseV2RelationshipsIapPriceSchedule(self):
        """Test InAppPurchaseV2RelationshipsIapPriceSchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
