# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.certificate_create_request_data_relationships import CertificateCreateRequestDataRelationships

class TestCertificateCreateRequestDataRelationships(unittest.TestCase):
    """CertificateCreateRequestDataRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CertificateCreateRequestDataRelationships:
        """Test CertificateCreateRequestDataRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CertificateCreateRequestDataRelationships`
        """
        model = CertificateCreateRequestDataRelationships()
        if include_optional:
            return CertificateCreateRequestDataRelationships(
                merchant_id = openapi_client.models.certificate_create_request_data_relationships_merchant_id.CertificateCreateRequest_data_relationships_merchantId(
                    data = openapi_client.models.certificate_create_request_data_relationships_merchant_id_data.CertificateCreateRequest_data_relationships_merchantId_data(
                        type = 'merchantIds', 
                        id = '', ), ),
                pass_type_id = openapi_client.models.certificate_create_request_data_relationships_pass_type_id.CertificateCreateRequest_data_relationships_passTypeId(
                    data = openapi_client.models.certificate_relationships_pass_type_id_data.Certificate_relationships_passTypeId_data(
                        type = 'passTypeIds', 
                        id = '', ), )
            )
        else:
            return CertificateCreateRequestDataRelationships(
        )
        """

    def testCertificateCreateRequestDataRelationships(self):
        """Test CertificateCreateRequestDataRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
