# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.beta_feedback_crash_submission_relationships_tester_data import BetaFeedbackCrashSubmissionRelationshipsTesterData

class TestBetaFeedbackCrashSubmissionRelationshipsTesterData(unittest.TestCase):
    """BetaFeedbackCrashSubmissionRelationshipsTesterData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetaFeedbackCrashSubmissionRelationshipsTesterData:
        """Test BetaFeedbackCrashSubmissionRelationshipsTesterData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetaFeedbackCrashSubmissionRelationshipsTesterData`
        """
        model = BetaFeedbackCrashSubmissionRelationshipsTesterData()
        if include_optional:
            return BetaFeedbackCrashSubmissionRelationshipsTesterData(
                type = 'betaTesters',
                id = ''
            )
        else:
            return BetaFeedbackCrashSubmissionRelationshipsTesterData(
                type = 'betaTesters',
                id = '',
        )
        """

    def testBetaFeedbackCrashSubmissionRelationshipsTesterData(self):
        """Test BetaFeedbackCrashSubmissionRelationshipsTesterData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
