# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.win_back_offers_api import WinBackOffersApi


class TestWinBackOffersApi(unittest.TestCase):
    """WinBackOffersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WinBackOffersApi()

    def tearDown(self) -> None:
        pass

    def test_win_back_offers_create_instance(self) -> None:
        """Test case for win_back_offers_create_instance

        """
        pass

    def test_win_back_offers_delete_instance(self) -> None:
        """Test case for win_back_offers_delete_instance

        """
        pass

    def test_win_back_offers_get_instance(self) -> None:
        """Test case for win_back_offers_get_instance

        """
        pass

    def test_win_back_offers_prices_get_to_many_related(self) -> None:
        """Test case for win_back_offers_prices_get_to_many_related

        """
        pass

    def test_win_back_offers_prices_get_to_many_relationship(self) -> None:
        """Test case for win_back_offers_prices_get_to_many_relationship

        """
        pass

    def test_win_back_offers_update_instance(self) -> None:
        """Test case for win_back_offers_update_instance

        """
        pass


if __name__ == '__main__':
    unittest.main()
