# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_clip_domain_status_attributes import AppClipDomainStatusAttributes

class TestAppClipDomainStatusAttributes(unittest.TestCase):
    """AppClipDomainStatusAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppClipDomainStatusAttributes:
        """Test AppClipDomainStatusAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppClipDomainStatusAttributes`
        """
        model = AppClipDomainStatusAttributes()
        if include_optional:
            return AppClipDomainStatusAttributes(
                domains = [
                    openapi_client.models.app_clip_domain_status_attributes_domains_inner.AppClipDomainStatus_attributes_domains_inner(
                        domain = '', 
                        is_valid = True, 
                        last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error_code = 'BAD_HTTP_RESPONSE', )
                    ],
                last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AppClipDomainStatusAttributes(
        )
        """

    def testAppClipDomainStatusAttributes(self):
        """Test AppClipDomainStatusAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
