# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscription_introductory_offer_relationships import SubscriptionIntroductoryOfferRelationships

class TestSubscriptionIntroductoryOfferRelationships(unittest.TestCase):
    """SubscriptionIntroductoryOfferRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionIntroductoryOfferRelationships:
        """Test SubscriptionIntroductoryOfferRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionIntroductoryOfferRelationships`
        """
        model = SubscriptionIntroductoryOfferRelationships()
        if include_optional:
            return SubscriptionIntroductoryOfferRelationships(
                subscription = openapi_client.models.promoted_purchase_relationships_subscription.PromotedPurchase_relationships_subscription(
                    data = openapi_client.models.promoted_purchase_relationships_subscription_data.PromotedPurchase_relationships_subscription_data(
                        type = 'subscriptions', 
                        id = '', ), ),
                territory = openapi_client.models.app_price_point_v3_relationships_territory.AppPricePointV3_relationships_territory(
                    data = openapi_client.models.app_price_point_v3_relationships_territory_data.AppPricePointV3_relationships_territory_data(
                        type = 'territories', 
                        id = '', ), ),
                subscription_price_point = openapi_client.models.subscription_introductory_offer_relationships_subscription_price_point.SubscriptionIntroductoryOffer_relationships_subscriptionPricePoint(
                    data = openapi_client.models.subscription_introductory_offer_relationships_subscription_price_point_data.SubscriptionIntroductoryOffer_relationships_subscriptionPricePoint_data(
                        type = 'subscriptionPricePoints', 
                        id = '', ), )
            )
        else:
            return SubscriptionIntroductoryOfferRelationships(
        )
        """

    def testSubscriptionIntroductoryOfferRelationships(self):
        """Test SubscriptionIntroductoryOfferRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
