# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ci_workflows_api import CiWorkflowsApi


class TestCiWorkflowsApi(unittest.TestCase):
    """CiWorkflowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CiWorkflowsApi()

    def tearDown(self) -> None:
        pass

    def test_ci_workflows_build_runs_get_to_many_related(self) -> None:
        """Test case for ci_workflows_build_runs_get_to_many_related

        """
        pass

    def test_ci_workflows_build_runs_get_to_many_relationship(self) -> None:
        """Test case for ci_workflows_build_runs_get_to_many_relationship

        """
        pass

    def test_ci_workflows_create_instance(self) -> None:
        """Test case for ci_workflows_create_instance

        """
        pass

    def test_ci_workflows_delete_instance(self) -> None:
        """Test case for ci_workflows_delete_instance

        """
        pass

    def test_ci_workflows_get_instance(self) -> None:
        """Test case for ci_workflows_get_instance

        """
        pass

    def test_ci_workflows_repository_get_to_one_related(self) -> None:
        """Test case for ci_workflows_repository_get_to_one_related

        """
        pass

    def test_ci_workflows_repository_get_to_one_relationship(self) -> None:
        """Test case for ci_workflows_repository_get_to_one_relationship

        """
        pass

    def test_ci_workflows_update_instance(self) -> None:
        """Test case for ci_workflows_update_instance

        """
        pass


if __name__ == '__main__':
    unittest.main()
