# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.beta_build_usages_v1_metric_response import BetaBuildUsagesV1MetricResponse

class TestBetaBuildUsagesV1MetricResponse(unittest.TestCase):
    """BetaBuildUsagesV1MetricResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetaBuildUsagesV1MetricResponse:
        """Test BetaBuildUsagesV1MetricResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetaBuildUsagesV1MetricResponse`
        """
        model = BetaBuildUsagesV1MetricResponse()
        if include_optional:
            return BetaBuildUsagesV1MetricResponse(
                data = [
                    openapi_client.models.beta_build_usages_v1_metric_response_data_inner.BetaBuildUsagesV1MetricResponse_data_inner(
                        data_points = openapi_client.models.beta_build_usages_v1_metric_response_data_inner_data_points.BetaBuildUsagesV1MetricResponse_data_inner_dataPoints(
                            start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            values = openapi_client.models.beta_build_usages_v1_metric_response_data_inner_data_points_values.BetaBuildUsagesV1MetricResponse_data_inner_dataPoints_values(
                                crash_count = 56, 
                                install_count = 56, 
                                session_count = 56, 
                                feedback_count = 56, 
                                invite_count = 56, ), ), )
                    ],
                links = openapi_client.models.paged_document_links.PagedDocumentLinks(
                    self = '', 
                    first = '', 
                    next = '', ),
                meta = openapi_client.models.paging_information.PagingInformation(
                    paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                        total = 56, 
                        limit = 56, 
                        next_cursor = '', ), )
            )
        else:
            return BetaBuildUsagesV1MetricResponse(
                data = [
                    openapi_client.models.beta_build_usages_v1_metric_response_data_inner.BetaBuildUsagesV1MetricResponse_data_inner(
                        data_points = openapi_client.models.beta_build_usages_v1_metric_response_data_inner_data_points.BetaBuildUsagesV1MetricResponse_data_inner_dataPoints(
                            start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            values = openapi_client.models.beta_build_usages_v1_metric_response_data_inner_data_points_values.BetaBuildUsagesV1MetricResponse_data_inner_dataPoints_values(
                                crash_count = 56, 
                                install_count = 56, 
                                session_count = 56, 
                                feedback_count = 56, 
                                invite_count = 56, ), ), )
                    ],
                links = openapi_client.models.paged_document_links.PagedDocumentLinks(
                    self = '', 
                    first = '', 
                    next = '', ),
        )
        """

    def testBetaBuildUsagesV1MetricResponse(self):
        """Test BetaBuildUsagesV1MetricResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
