# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.beta_groups_api import BetaGroupsApi


class TestBetaGroupsApi(unittest.TestCase):
    """BetaGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BetaGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_beta_groups_app_get_to_one_related(self) -> None:
        """Test case for beta_groups_app_get_to_one_related

        """
        pass

    def test_beta_groups_app_get_to_one_relationship(self) -> None:
        """Test case for beta_groups_app_get_to_one_relationship

        """
        pass

    def test_beta_groups_beta_recruitment_criteria_get_to_one_related(self) -> None:
        """Test case for beta_groups_beta_recruitment_criteria_get_to_one_related

        """
        pass

    def test_beta_groups_beta_recruitment_criteria_get_to_one_relationship(self) -> None:
        """Test case for beta_groups_beta_recruitment_criteria_get_to_one_relationship

        """
        pass

    def test_beta_groups_beta_recruitment_criterion_compatible_build_check_get_to_one_related(self) -> None:
        """Test case for beta_groups_beta_recruitment_criterion_compatible_build_check_get_to_one_related

        """
        pass

    def test_beta_groups_beta_recruitment_criterion_compatible_build_check_get_to_one_relationship(self) -> None:
        """Test case for beta_groups_beta_recruitment_criterion_compatible_build_check_get_to_one_relationship

        """
        pass

    def test_beta_groups_beta_tester_usages_get_metrics(self) -> None:
        """Test case for beta_groups_beta_tester_usages_get_metrics

        """
        pass

    def test_beta_groups_beta_testers_create_to_many_relationship(self) -> None:
        """Test case for beta_groups_beta_testers_create_to_many_relationship

        """
        pass

    def test_beta_groups_beta_testers_delete_to_many_relationship(self) -> None:
        """Test case for beta_groups_beta_testers_delete_to_many_relationship

        """
        pass

    def test_beta_groups_beta_testers_get_to_many_related(self) -> None:
        """Test case for beta_groups_beta_testers_get_to_many_related

        """
        pass

    def test_beta_groups_beta_testers_get_to_many_relationship(self) -> None:
        """Test case for beta_groups_beta_testers_get_to_many_relationship

        """
        pass

    def test_beta_groups_builds_create_to_many_relationship(self) -> None:
        """Test case for beta_groups_builds_create_to_many_relationship

        """
        pass

    def test_beta_groups_builds_delete_to_many_relationship(self) -> None:
        """Test case for beta_groups_builds_delete_to_many_relationship

        """
        pass

    def test_beta_groups_builds_get_to_many_related(self) -> None:
        """Test case for beta_groups_builds_get_to_many_related

        """
        pass

    def test_beta_groups_builds_get_to_many_relationship(self) -> None:
        """Test case for beta_groups_builds_get_to_many_relationship

        """
        pass

    def test_beta_groups_create_instance(self) -> None:
        """Test case for beta_groups_create_instance

        """
        pass

    def test_beta_groups_delete_instance(self) -> None:
        """Test case for beta_groups_delete_instance

        """
        pass

    def test_beta_groups_get_collection(self) -> None:
        """Test case for beta_groups_get_collection

        """
        pass

    def test_beta_groups_get_instance(self) -> None:
        """Test case for beta_groups_get_instance

        """
        pass

    def test_beta_groups_public_link_usages_get_metrics(self) -> None:
        """Test case for beta_groups_public_link_usages_get_metrics

        """
        pass

    def test_beta_groups_update_instance(self) -> None:
        """Test case for beta_groups_update_instance

        """
        pass


if __name__ == '__main__':
    unittest.main()
