# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.webhook_ping_create_request import WebhookPingCreateRequest

class TestWebhookPingCreateRequest(unittest.TestCase):
    """WebhookPingCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookPingCreateRequest:
        """Test WebhookPingCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookPingCreateRequest`
        """
        model = WebhookPingCreateRequest()
        if include_optional:
            return WebhookPingCreateRequest(
                data = openapi_client.models.webhook_ping_create_request_data.WebhookPingCreateRequest_data(
                    type = 'webhookPings', 
                    relationships = openapi_client.models.webhook_ping_create_request_data_relationships.WebhookPingCreateRequest_data_relationships(
                        webhook = openapi_client.models.webhook_ping_create_request_data_relationships_webhook.WebhookPingCreateRequest_data_relationships_webhook(
                            data = openapi_client.models.webhook_ping_create_request_data_relationships_webhook_data.WebhookPingCreateRequest_data_relationships_webhook_data(
                                type = 'webhooks', 
                                id = '', ), ), ), )
            )
        else:
            return WebhookPingCreateRequest(
                data = openapi_client.models.webhook_ping_create_request_data.WebhookPingCreateRequest_data(
                    type = 'webhookPings', 
                    relationships = openapi_client.models.webhook_ping_create_request_data_relationships.WebhookPingCreateRequest_data_relationships(
                        webhook = openapi_client.models.webhook_ping_create_request_data_relationships_webhook.WebhookPingCreateRequest_data_relationships_webhook(
                            data = openapi_client.models.webhook_ping_create_request_data_relationships_webhook_data.WebhookPingCreateRequest_data_relationships_webhook_data(
                                type = 'webhooks', 
                                id = '', ), ), ), ),
        )
        """

    def testWebhookPingCreateRequest(self):
        """Test WebhookPingCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
