# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_matchmaking_test_request_inline_create import GameCenterMatchmakingTestRequestInlineCreate

class TestGameCenterMatchmakingTestRequestInlineCreate(unittest.TestCase):
    """GameCenterMatchmakingTestRequestInlineCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterMatchmakingTestRequestInlineCreate:
        """Test GameCenterMatchmakingTestRequestInlineCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterMatchmakingTestRequestInlineCreate`
        """
        model = GameCenterMatchmakingTestRequestInlineCreate()
        if include_optional:
            return GameCenterMatchmakingTestRequestInlineCreate(
                type = 'gameCenterMatchmakingTestRequests',
                id = '',
                attributes = openapi_client.models.game_center_matchmaking_test_request_inline_create_attributes.GameCenterMatchmakingTestRequestInlineCreate_attributes(
                    request_name = '', 
                    seconds_in_queue = 56, 
                    locale = 'AR-SA', 
                    location = openapi_client.models.location.Location(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    min_players = 56, 
                    max_players = 56, 
                    player_count = 56, 
                    bundle_id = '', 
                    platform = 'IOS', 
                    app_version = '', ),
                relationships = openapi_client.models.game_center_matchmaking_test_request_inline_create_relationships.GameCenterMatchmakingTestRequestInlineCreate_relationships(
                    matchmaking_player_properties = openapi_client.models.game_center_matchmaking_test_request_inline_create_relationships_matchmaking_player_properties.GameCenterMatchmakingTestRequestInlineCreate_relationships_matchmakingPlayerProperties(
                        data = [
                            openapi_client.models.game_center_matchmaking_test_request_inline_create_relationships_matchmaking_player_properties_data_inner.GameCenterMatchmakingTestRequestInlineCreate_relationships_matchmakingPlayerProperties_data_inner(
                                type = 'gameCenterMatchmakingTestPlayerProperties', 
                                id = '', )
                            ], ), )
            )
        else:
            return GameCenterMatchmakingTestRequestInlineCreate(
                type = 'gameCenterMatchmakingTestRequests',
                attributes = openapi_client.models.game_center_matchmaking_test_request_inline_create_attributes.GameCenterMatchmakingTestRequestInlineCreate_attributes(
                    request_name = '', 
                    seconds_in_queue = 56, 
                    locale = 'AR-SA', 
                    location = openapi_client.models.location.Location(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    min_players = 56, 
                    max_players = 56, 
                    player_count = 56, 
                    bundle_id = '', 
                    platform = 'IOS', 
                    app_version = '', ),
        )
        """

    def testGameCenterMatchmakingTestRequestInlineCreate(self):
        """Test GameCenterMatchmakingTestRequestInlineCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
