# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.in_app_purchase_price_schedule_create_request_data_relationships_manual_prices import InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices

class TestInAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices(unittest.TestCase):
    """InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices:
        """Test InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices`
        """
        model = InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices()
        if include_optional:
            return InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices(
                data = [
                    openapi_client.models.in_app_purchase_price_schedule_relationships_manual_prices_data_inner.InAppPurchasePriceSchedule_relationships_manualPrices_data_inner(
                        type = 'inAppPurchasePrices', 
                        id = '', )
                    ]
            )
        else:
            return InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices(
                data = [
                    openapi_client.models.in_app_purchase_price_schedule_relationships_manual_prices_data_inner.InAppPurchasePriceSchedule_relationships_manualPrices_data_inner(
                        type = 'inAppPurchasePrices', 
                        id = '', )
                    ],
        )
        """

    def testInAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices(self):
        """Test InAppPurchasePriceScheduleCreateRequestDataRelationshipsManualPrices"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
