# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.in_app_purchase_submissions_api import InAppPurchaseSubmissionsApi


class TestInAppPurchaseSubmissionsApi(unittest.TestCase):
    """InAppPurchaseSubmissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InAppPurchaseSubmissionsApi()

    def tearDown(self) -> None:
        pass

    def test_in_app_purchase_submissions_create_instance(self) -> None:
        """Test case for in_app_purchase_submissions_create_instance

        """
        pass


if __name__ == '__main__':
    unittest.main()
