# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.in_app_purchase_v2_iap_price_schedule_linkage_response import InAppPurchaseV2IapPriceScheduleLinkageResponse

class TestInAppPurchaseV2IapPriceScheduleLinkageResponse(unittest.TestCase):
    """InAppPurchaseV2IapPriceScheduleLinkageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InAppPurchaseV2IapPriceScheduleLinkageResponse:
        """Test InAppPurchaseV2IapPriceScheduleLinkageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InAppPurchaseV2IapPriceScheduleLinkageResponse`
        """
        model = InAppPurchaseV2IapPriceScheduleLinkageResponse()
        if include_optional:
            return InAppPurchaseV2IapPriceScheduleLinkageResponse(
                data = openapi_client.models.in_app_purchase_v2_relationships_iap_price_schedule_data.InAppPurchaseV2_relationships_iapPriceSchedule_data(
                    type = 'inAppPurchasePriceSchedules', 
                    id = '', ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', )
            )
        else:
            return InAppPurchaseV2IapPriceScheduleLinkageResponse(
                data = openapi_client.models.in_app_purchase_v2_relationships_iap_price_schedule_data.InAppPurchaseV2_relationships_iapPriceSchedule_data(
                    type = 'inAppPurchasePriceSchedules', 
                    id = '', ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', ),
        )
        """

    def testInAppPurchaseV2IapPriceScheduleLinkageResponse(self):
        """Test InAppPurchaseV2IapPriceScheduleLinkageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
