# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_leaderboard_image_create_request import GameCenterLeaderboardImageCreateRequest

class TestGameCenterLeaderboardImageCreateRequest(unittest.TestCase):
    """GameCenterLeaderboardImageCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterLeaderboardImageCreateRequest:
        """Test GameCenterLeaderboardImageCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterLeaderboardImageCreateRequest`
        """
        model = GameCenterLeaderboardImageCreateRequest()
        if include_optional:
            return GameCenterLeaderboardImageCreateRequest(
                data = openapi_client.models.game_center_leaderboard_image_create_request_data.GameCenterLeaderboardImageCreateRequest_data(
                    type = 'gameCenterLeaderboardImages', 
                    attributes = openapi_client.models.app_clip_advanced_experience_image_create_request_data_attributes.AppClipAdvancedExperienceImageCreateRequest_data_attributes(
                        file_size = 56, 
                        file_name = '', ), 
                    relationships = openapi_client.models.game_center_leaderboard_image_create_request_data_relationships.GameCenterLeaderboardImageCreateRequest_data_relationships(
                        game_center_leaderboard_localization = openapi_client.models.game_center_leaderboard_image_create_request_data_relationships_game_center_leaderboard_localization.GameCenterLeaderboardImageCreateRequest_data_relationships_gameCenterLeaderboardLocalization(
                            data = openapi_client.models.game_center_leaderboard_image_relationships_game_center_leaderboard_localization_data.GameCenterLeaderboardImage_relationships_gameCenterLeaderboardLocalization_data(
                                type = 'gameCenterLeaderboardLocalizations', 
                                id = '', ), ), ), )
            )
        else:
            return GameCenterLeaderboardImageCreateRequest(
                data = openapi_client.models.game_center_leaderboard_image_create_request_data.GameCenterLeaderboardImageCreateRequest_data(
                    type = 'gameCenterLeaderboardImages', 
                    attributes = openapi_client.models.app_clip_advanced_experience_image_create_request_data_attributes.AppClipAdvancedExperienceImageCreateRequest_data_attributes(
                        file_size = 56, 
                        file_name = '', ), 
                    relationships = openapi_client.models.game_center_leaderboard_image_create_request_data_relationships.GameCenterLeaderboardImageCreateRequest_data_relationships(
                        game_center_leaderboard_localization = openapi_client.models.game_center_leaderboard_image_create_request_data_relationships_game_center_leaderboard_localization.GameCenterLeaderboardImageCreateRequest_data_relationships_gameCenterLeaderboardLocalization(
                            data = openapi_client.models.game_center_leaderboard_image_relationships_game_center_leaderboard_localization_data.GameCenterLeaderboardImage_relationships_gameCenterLeaderboardLocalization_data(
                                type = 'gameCenterLeaderboardLocalizations', 
                                id = '', ), ), ), ),
        )
        """

    def testGameCenterLeaderboardImageCreateRequest(self):
        """Test GameCenterLeaderboardImageCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
