# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.apps_api import AppsApi


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppsApi()

    def tearDown(self) -> None:
        pass

    def test_apps_accessibility_declarations_get_to_many_related(self) -> None:
        """Test case for apps_accessibility_declarations_get_to_many_related

        """
        pass

    def test_apps_accessibility_declarations_get_to_many_relationship(self) -> None:
        """Test case for apps_accessibility_declarations_get_to_many_relationship

        """
        pass

    def test_apps_alternative_distribution_key_get_to_one_related(self) -> None:
        """Test case for apps_alternative_distribution_key_get_to_one_related

        """
        pass

    def test_apps_alternative_distribution_key_get_to_one_relationship(self) -> None:
        """Test case for apps_alternative_distribution_key_get_to_one_relationship

        """
        pass

    def test_apps_analytics_report_requests_get_to_many_related(self) -> None:
        """Test case for apps_analytics_report_requests_get_to_many_related

        """
        pass

    def test_apps_analytics_report_requests_get_to_many_relationship(self) -> None:
        """Test case for apps_analytics_report_requests_get_to_many_relationship

        """
        pass

    def test_apps_app_availability_v2_get_to_one_related(self) -> None:
        """Test case for apps_app_availability_v2_get_to_one_related

        """
        pass

    def test_apps_app_availability_v2_get_to_one_relationship(self) -> None:
        """Test case for apps_app_availability_v2_get_to_one_relationship

        """
        pass

    def test_apps_app_clips_get_to_many_related(self) -> None:
        """Test case for apps_app_clips_get_to_many_related

        """
        pass

    def test_apps_app_clips_get_to_many_relationship(self) -> None:
        """Test case for apps_app_clips_get_to_many_relationship

        """
        pass

    def test_apps_app_custom_product_pages_get_to_many_related(self) -> None:
        """Test case for apps_app_custom_product_pages_get_to_many_related

        """
        pass

    def test_apps_app_custom_product_pages_get_to_many_relationship(self) -> None:
        """Test case for apps_app_custom_product_pages_get_to_many_relationship

        """
        pass

    def test_apps_app_encryption_declarations_get_to_many_related(self) -> None:
        """Test case for apps_app_encryption_declarations_get_to_many_related

        """
        pass

    def test_apps_app_encryption_declarations_get_to_many_relationship(self) -> None:
        """Test case for apps_app_encryption_declarations_get_to_many_relationship

        """
        pass

    def test_apps_app_events_get_to_many_related(self) -> None:
        """Test case for apps_app_events_get_to_many_related

        """
        pass

    def test_apps_app_events_get_to_many_relationship(self) -> None:
        """Test case for apps_app_events_get_to_many_relationship

        """
        pass

    def test_apps_app_infos_get_to_many_related(self) -> None:
        """Test case for apps_app_infos_get_to_many_related

        """
        pass

    def test_apps_app_infos_get_to_many_relationship(self) -> None:
        """Test case for apps_app_infos_get_to_many_relationship

        """
        pass

    def test_apps_app_price_points_get_to_many_related(self) -> None:
        """Test case for apps_app_price_points_get_to_many_related

        """
        pass

    def test_apps_app_price_points_get_to_many_relationship(self) -> None:
        """Test case for apps_app_price_points_get_to_many_relationship

        """
        pass

    def test_apps_app_price_schedule_get_to_one_related(self) -> None:
        """Test case for apps_app_price_schedule_get_to_one_related

        """
        pass

    def test_apps_app_price_schedule_get_to_one_relationship(self) -> None:
        """Test case for apps_app_price_schedule_get_to_one_relationship

        """
        pass

    def test_apps_app_store_version_experiments_v2_get_to_many_related(self) -> None:
        """Test case for apps_app_store_version_experiments_v2_get_to_many_related

        """
        pass

    def test_apps_app_store_version_experiments_v2_get_to_many_relationship(self) -> None:
        """Test case for apps_app_store_version_experiments_v2_get_to_many_relationship

        """
        pass

    def test_apps_app_store_versions_get_to_many_related(self) -> None:
        """Test case for apps_app_store_versions_get_to_many_related

        """
        pass

    def test_apps_app_store_versions_get_to_many_relationship(self) -> None:
        """Test case for apps_app_store_versions_get_to_many_relationship

        """
        pass

    def test_apps_background_assets_get_to_many_related(self) -> None:
        """Test case for apps_background_assets_get_to_many_related

        """
        pass

    def test_apps_background_assets_get_to_many_relationship(self) -> None:
        """Test case for apps_background_assets_get_to_many_relationship

        """
        pass

    def test_apps_beta_app_localizations_get_to_many_related(self) -> None:
        """Test case for apps_beta_app_localizations_get_to_many_related

        """
        pass

    def test_apps_beta_app_localizations_get_to_many_relationship(self) -> None:
        """Test case for apps_beta_app_localizations_get_to_many_relationship

        """
        pass

    def test_apps_beta_app_review_detail_get_to_one_related(self) -> None:
        """Test case for apps_beta_app_review_detail_get_to_one_related

        """
        pass

    def test_apps_beta_app_review_detail_get_to_one_relationship(self) -> None:
        """Test case for apps_beta_app_review_detail_get_to_one_relationship

        """
        pass

    def test_apps_beta_feedback_crash_submissions_get_to_many_related(self) -> None:
        """Test case for apps_beta_feedback_crash_submissions_get_to_many_related

        """
        pass

    def test_apps_beta_feedback_crash_submissions_get_to_many_relationship(self) -> None:
        """Test case for apps_beta_feedback_crash_submissions_get_to_many_relationship

        """
        pass

    def test_apps_beta_feedback_screenshot_submissions_get_to_many_related(self) -> None:
        """Test case for apps_beta_feedback_screenshot_submissions_get_to_many_related

        """
        pass

    def test_apps_beta_feedback_screenshot_submissions_get_to_many_relationship(self) -> None:
        """Test case for apps_beta_feedback_screenshot_submissions_get_to_many_relationship

        """
        pass

    def test_apps_beta_groups_get_to_many_related(self) -> None:
        """Test case for apps_beta_groups_get_to_many_related

        """
        pass

    def test_apps_beta_groups_get_to_many_relationship(self) -> None:
        """Test case for apps_beta_groups_get_to_many_relationship

        """
        pass

    def test_apps_beta_license_agreement_get_to_one_related(self) -> None:
        """Test case for apps_beta_license_agreement_get_to_one_related

        """
        pass

    def test_apps_beta_license_agreement_get_to_one_relationship(self) -> None:
        """Test case for apps_beta_license_agreement_get_to_one_relationship

        """
        pass

    def test_apps_beta_tester_usages_get_metrics(self) -> None:
        """Test case for apps_beta_tester_usages_get_metrics

        """
        pass

    def test_apps_beta_testers_delete_to_many_relationship(self) -> None:
        """Test case for apps_beta_testers_delete_to_many_relationship

        """
        pass

    def test_apps_builds_get_to_many_related(self) -> None:
        """Test case for apps_builds_get_to_many_related

        """
        pass

    def test_apps_builds_get_to_many_relationship(self) -> None:
        """Test case for apps_builds_get_to_many_relationship

        """
        pass

    def test_apps_ci_product_get_to_one_related(self) -> None:
        """Test case for apps_ci_product_get_to_one_related

        """
        pass

    def test_apps_ci_product_get_to_one_relationship(self) -> None:
        """Test case for apps_ci_product_get_to_one_relationship

        """
        pass

    def test_apps_customer_review_summarizations_get_to_many_related(self) -> None:
        """Test case for apps_customer_review_summarizations_get_to_many_related

        """
        pass

    def test_apps_customer_reviews_get_to_many_related(self) -> None:
        """Test case for apps_customer_reviews_get_to_many_related

        """
        pass

    def test_apps_customer_reviews_get_to_many_relationship(self) -> None:
        """Test case for apps_customer_reviews_get_to_many_relationship

        """
        pass

    def test_apps_end_user_license_agreement_get_to_one_related(self) -> None:
        """Test case for apps_end_user_license_agreement_get_to_one_related

        """
        pass

    def test_apps_end_user_license_agreement_get_to_one_relationship(self) -> None:
        """Test case for apps_end_user_license_agreement_get_to_one_relationship

        """
        pass

    def test_apps_game_center_detail_get_to_one_related(self) -> None:
        """Test case for apps_game_center_detail_get_to_one_related

        """
        pass

    def test_apps_game_center_detail_get_to_one_relationship(self) -> None:
        """Test case for apps_game_center_detail_get_to_one_relationship

        """
        pass

    def test_apps_game_center_enabled_versions_get_to_many_related(self) -> None:
        """Test case for apps_game_center_enabled_versions_get_to_many_related

        """
        pass

    def test_apps_game_center_enabled_versions_get_to_many_relationship(self) -> None:
        """Test case for apps_game_center_enabled_versions_get_to_many_relationship

        """
        pass

    def test_apps_get_collection(self) -> None:
        """Test case for apps_get_collection

        """
        pass

    def test_apps_get_instance(self) -> None:
        """Test case for apps_get_instance

        """
        pass

    def test_apps_in_app_purchases_get_to_many_related(self) -> None:
        """Test case for apps_in_app_purchases_get_to_many_related

        """
        pass

    def test_apps_in_app_purchases_get_to_many_relationship(self) -> None:
        """Test case for apps_in_app_purchases_get_to_many_relationship

        """
        pass

    def test_apps_in_app_purchases_v2_get_to_many_related(self) -> None:
        """Test case for apps_in_app_purchases_v2_get_to_many_related

        """
        pass

    def test_apps_in_app_purchases_v2_get_to_many_relationship(self) -> None:
        """Test case for apps_in_app_purchases_v2_get_to_many_relationship

        """
        pass

    def test_apps_marketplace_search_detail_get_to_one_related(self) -> None:
        """Test case for apps_marketplace_search_detail_get_to_one_related

        """
        pass

    def test_apps_marketplace_search_detail_get_to_one_relationship(self) -> None:
        """Test case for apps_marketplace_search_detail_get_to_one_relationship

        """
        pass

    def test_apps_perf_power_metrics_get_to_many_related(self) -> None:
        """Test case for apps_perf_power_metrics_get_to_many_related

        """
        pass

    def test_apps_pre_release_versions_get_to_many_related(self) -> None:
        """Test case for apps_pre_release_versions_get_to_many_related

        """
        pass

    def test_apps_pre_release_versions_get_to_many_relationship(self) -> None:
        """Test case for apps_pre_release_versions_get_to_many_relationship

        """
        pass

    def test_apps_promoted_purchases_get_to_many_related(self) -> None:
        """Test case for apps_promoted_purchases_get_to_many_related

        """
        pass

    def test_apps_promoted_purchases_get_to_many_relationship(self) -> None:
        """Test case for apps_promoted_purchases_get_to_many_relationship

        """
        pass

    def test_apps_promoted_purchases_replace_to_many_relationship(self) -> None:
        """Test case for apps_promoted_purchases_replace_to_many_relationship

        """
        pass

    def test_apps_review_submissions_get_to_many_related(self) -> None:
        """Test case for apps_review_submissions_get_to_many_related

        """
        pass

    def test_apps_review_submissions_get_to_many_relationship(self) -> None:
        """Test case for apps_review_submissions_get_to_many_relationship

        """
        pass

    def test_apps_subscription_grace_period_get_to_one_related(self) -> None:
        """Test case for apps_subscription_grace_period_get_to_one_related

        """
        pass

    def test_apps_subscription_grace_period_get_to_one_relationship(self) -> None:
        """Test case for apps_subscription_grace_period_get_to_one_relationship

        """
        pass

    def test_apps_subscription_groups_get_to_many_related(self) -> None:
        """Test case for apps_subscription_groups_get_to_many_related

        """
        pass

    def test_apps_subscription_groups_get_to_many_relationship(self) -> None:
        """Test case for apps_subscription_groups_get_to_many_relationship

        """
        pass

    def test_apps_update_instance(self) -> None:
        """Test case for apps_update_instance

        """
        pass

    def test_apps_webhooks_get_to_many_related(self) -> None:
        """Test case for apps_webhooks_get_to_many_related

        """
        pass

    def test_apps_webhooks_get_to_many_relationship(self) -> None:
        """Test case for apps_webhooks_get_to_many_relationship

        """
        pass


if __name__ == '__main__':
    unittest.main()
