# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.nomination_relationships import NominationRelationships

class TestNominationRelationships(unittest.TestCase):
    """NominationRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NominationRelationships:
        """Test NominationRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NominationRelationships`
        """
        model = NominationRelationships()
        if include_optional:
            return NominationRelationships(
                related_apps = openapi_client.models.in_app_purchase_relationships_apps.InAppPurchase_relationships_apps(
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                            type = 'apps', 
                            id = '', )
                        ], ),
                created_by_actor = openapi_client.models.nomination_relationships_created_by_actor.Nomination_relationships_createdByActor(
                    data = openapi_client.models.nomination_relationships_created_by_actor_data.Nomination_relationships_createdByActor_data(
                        type = 'actors', 
                        id = '', ), ),
                last_modified_by_actor = openapi_client.models.nomination_relationships_created_by_actor.Nomination_relationships_createdByActor(
                    data = openapi_client.models.nomination_relationships_created_by_actor_data.Nomination_relationships_createdByActor_data(
                        type = 'actors', 
                        id = '', ), ),
                submitted_by_actor = openapi_client.models.nomination_relationships_created_by_actor.Nomination_relationships_createdByActor(
                    data = openapi_client.models.nomination_relationships_created_by_actor_data.Nomination_relationships_createdByActor_data(
                        type = 'actors', 
                        id = '', ), ),
                in_app_events = openapi_client.models.nomination_relationships_in_app_events.Nomination_relationships_inAppEvents(
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.app_event_localization_relationships_app_event_data.AppEventLocalization_relationships_appEvent_data(
                            type = 'appEvents', 
                            id = '', )
                        ], ),
                supported_territories = openapi_client.models.nomination_relationships_supported_territories.Nomination_relationships_supportedTerritories(
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.app_price_point_v3_relationships_territory_data.AppPricePointV3_relationships_territory_data(
                            type = 'territories', 
                            id = '', )
                        ], )
            )
        else:
            return NominationRelationships(
        )
        """

    def testNominationRelationships(self):
        """Test NominationRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
