# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.accessibility_declaration_create_request_data_attributes import AccessibilityDeclarationCreateRequestDataAttributes

class TestAccessibilityDeclarationCreateRequestDataAttributes(unittest.TestCase):
    """AccessibilityDeclarationCreateRequestDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessibilityDeclarationCreateRequestDataAttributes:
        """Test AccessibilityDeclarationCreateRequestDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessibilityDeclarationCreateRequestDataAttributes`
        """
        model = AccessibilityDeclarationCreateRequestDataAttributes()
        if include_optional:
            return AccessibilityDeclarationCreateRequestDataAttributes(
                device_family = 'IPHONE',
                supports_audio_descriptions = True,
                supports_captions = True,
                supports_dark_interface = True,
                supports_differentiate_without_color_alone = True,
                supports_larger_text = True,
                supports_reduced_motion = True,
                supports_sufficient_contrast = True,
                supports_voice_control = True,
                supports_voiceover = True
            )
        else:
            return AccessibilityDeclarationCreateRequestDataAttributes(
                device_family = 'IPHONE',
        )
        """

    def testAccessibilityDeclarationCreateRequestDataAttributes(self):
        """Test AccessibilityDeclarationCreateRequestDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
