# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_price_v2_attributes import AppPriceV2Attributes

class TestAppPriceV2Attributes(unittest.TestCase):
    """AppPriceV2Attributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppPriceV2Attributes:
        """Test AppPriceV2Attributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppPriceV2Attributes`
        """
        model = AppPriceV2Attributes()
        if include_optional:
            return AppPriceV2Attributes(
                manual = True,
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return AppPriceV2Attributes(
        )
        """

    def testAppPriceV2Attributes(self):
        """Test AppPriceV2Attributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
