# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.analytics_report import AnalyticsReport

class TestAnalyticsReport(unittest.TestCase):
    """AnalyticsReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsReport:
        """Test AnalyticsReport
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsReport`
        """
        model = AnalyticsReport()
        if include_optional:
            return AnalyticsReport(
                type = 'analyticsReports',
                id = '',
                attributes = openapi_client.models.analytics_report_attributes.AnalyticsReport_attributes(
                    name = '', 
                    category = 'APP_USAGE', ),
                relationships = openapi_client.models.analytics_report_relationships.AnalyticsReport_relationships(
                    instances = openapi_client.models.analytics_report_instance_relationships_segments.AnalyticsReportInstance_relationships_segments(
                        links = openapi_client.models.relationship_links.RelationshipLinks(
                            self = '', 
                            related = '', ), ), ),
                links = openapi_client.models.resource_links.ResourceLinks(
                    self = '', )
            )
        else:
            return AnalyticsReport(
                type = 'analyticsReports',
                id = '',
        )
        """

    def testAnalyticsReport(self):
        """Test AnalyticsReport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
