# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.end_user_license_agreement_response import EndUserLicenseAgreementResponse

class TestEndUserLicenseAgreementResponse(unittest.TestCase):
    """EndUserLicenseAgreementResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EndUserLicenseAgreementResponse:
        """Test EndUserLicenseAgreementResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EndUserLicenseAgreementResponse`
        """
        model = EndUserLicenseAgreementResponse()
        if include_optional:
            return EndUserLicenseAgreementResponse(
                data = openapi_client.models.end_user_license_agreement.EndUserLicenseAgreement(
                    type = 'endUserLicenseAgreements', 
                    id = '', 
                    attributes = openapi_client.models.beta_license_agreement_attributes.BetaLicenseAgreement_attributes(
                        agreement_text = '', ), 
                    relationships = openapi_client.models.end_user_license_agreement_relationships.EndUserLicenseAgreement_relationships(
                        app = openapi_client.models.alternative_distribution_key_create_request_data_relationships_app.AlternativeDistributionKeyCreateRequest_data_relationships_app(
                            data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                                type = 'apps', 
                                id = '', ), ), 
                        territories = openapi_client.models.end_user_license_agreement_relationships_territories.EndUserLicenseAgreement_relationships_territories(
                            links = openapi_client.models.relationship_links.RelationshipLinks(
                                self = '', 
                                related = '', ), 
                            meta = openapi_client.models.paging_information.PagingInformation(
                                paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                                    total = 56, 
                                    limit = 56, 
                                    next_cursor = '', ), ), ), ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                included = [
                    null
                    ],
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', )
            )
        else:
            return EndUserLicenseAgreementResponse(
                data = openapi_client.models.end_user_license_agreement.EndUserLicenseAgreement(
                    type = 'endUserLicenseAgreements', 
                    id = '', 
                    attributes = openapi_client.models.beta_license_agreement_attributes.BetaLicenseAgreement_attributes(
                        agreement_text = '', ), 
                    relationships = openapi_client.models.end_user_license_agreement_relationships.EndUserLicenseAgreement_relationships(
                        app = openapi_client.models.alternative_distribution_key_create_request_data_relationships_app.AlternativeDistributionKeyCreateRequest_data_relationships_app(
                            data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                                type = 'apps', 
                                id = '', ), ), 
                        territories = openapi_client.models.end_user_license_agreement_relationships_territories.EndUserLicenseAgreement_relationships_territories(
                            links = openapi_client.models.relationship_links.RelationshipLinks(
                                self = '', 
                                related = '', ), 
                            meta = openapi_client.models.paging_information.PagingInformation(
                                paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                                    total = 56, 
                                    limit = 56, 
                                    next_cursor = '', ), ), ), ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', ),
        )
        """

    def testEndUserLicenseAgreementResponse(self):
        """Test EndUserLicenseAgreementResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
