# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.marketplace_search_details_api import MarketplaceSearchDetailsApi


class TestMarketplaceSearchDetailsApi(unittest.TestCase):
    """MarketplaceSearchDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketplaceSearchDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_marketplace_search_details_create_instance(self) -> None:
        """Test case for marketplace_search_details_create_instance

        """
        pass

    def test_marketplace_search_details_delete_instance(self) -> None:
        """Test case for marketplace_search_details_delete_instance

        """
        pass

    def test_marketplace_search_details_update_instance(self) -> None:
        """Test case for marketplace_search_details_update_instance

        """
        pass


if __name__ == '__main__':
    unittest.main()
