# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.promoted_purchase_create_request_data import PromotedPurchaseCreateRequestData

class TestPromotedPurchaseCreateRequestData(unittest.TestCase):
    """PromotedPurchaseCreateRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromotedPurchaseCreateRequestData:
        """Test PromotedPurchaseCreateRequestData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromotedPurchaseCreateRequestData`
        """
        model = PromotedPurchaseCreateRequestData()
        if include_optional:
            return PromotedPurchaseCreateRequestData(
                type = 'promotedPurchases',
                attributes = openapi_client.models.promoted_purchase_create_request_data_attributes.PromotedPurchaseCreateRequest_data_attributes(
                    visible_for_all_users = True, 
                    enabled = True, ),
                relationships = openapi_client.models.promoted_purchase_create_request_data_relationships.PromotedPurchaseCreateRequest_data_relationships(
                    app = openapi_client.models.accessibility_declaration_create_request_data_relationships_app.AccessibilityDeclarationCreateRequest_data_relationships_app(
                        data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                            type = 'apps', 
                            id = '', ), ), 
                    in_app_purchase_v2 = openapi_client.models.in_app_purchase_app_store_review_screenshot_relationships_in_app_purchase_v2.InAppPurchaseAppStoreReviewScreenshot_relationships_inAppPurchaseV2(), 
                    subscription = openapi_client.models.promoted_purchase_relationships_subscription.PromotedPurchase_relationships_subscription(), )
            )
        else:
            return PromotedPurchaseCreateRequestData(
                type = 'promotedPurchases',
                attributes = openapi_client.models.promoted_purchase_create_request_data_attributes.PromotedPurchaseCreateRequest_data_attributes(
                    visible_for_all_users = True, 
                    enabled = True, ),
                relationships = openapi_client.models.promoted_purchase_create_request_data_relationships.PromotedPurchaseCreateRequest_data_relationships(
                    app = openapi_client.models.accessibility_declaration_create_request_data_relationships_app.AccessibilityDeclarationCreateRequest_data_relationships_app(
                        data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                            type = 'apps', 
                            id = '', ), ), 
                    in_app_purchase_v2 = openapi_client.models.in_app_purchase_app_store_review_screenshot_relationships_in_app_purchase_v2.InAppPurchaseAppStoreReviewScreenshot_relationships_inAppPurchaseV2(), 
                    subscription = openapi_client.models.promoted_purchase_relationships_subscription.PromotedPurchase_relationships_subscription(), ),
        )
        """

    def testPromotedPurchaseCreateRequestData(self):
        """Test PromotedPurchaseCreateRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
