# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.beta_recruitment_criterion_compatible_build_check_attributes import BetaRecruitmentCriterionCompatibleBuildCheckAttributes

class TestBetaRecruitmentCriterionCompatibleBuildCheckAttributes(unittest.TestCase):
    """BetaRecruitmentCriterionCompatibleBuildCheckAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetaRecruitmentCriterionCompatibleBuildCheckAttributes:
        """Test BetaRecruitmentCriterionCompatibleBuildCheckAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetaRecruitmentCriterionCompatibleBuildCheckAttributes`
        """
        model = BetaRecruitmentCriterionCompatibleBuildCheckAttributes()
        if include_optional:
            return BetaRecruitmentCriterionCompatibleBuildCheckAttributes(
                has_compatible_build = True
            )
        else:
            return BetaRecruitmentCriterionCompatibleBuildCheckAttributes(
        )
        """

    def testBetaRecruitmentCriterionCompatibleBuildCheckAttributes(self):
        """Test BetaRecruitmentCriterionCompatibleBuildCheckAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
