# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.beta_app_clip_invocation_localization import BetaAppClipInvocationLocalization

class TestBetaAppClipInvocationLocalization(unittest.TestCase):
    """BetaAppClipInvocationLocalization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetaAppClipInvocationLocalization:
        """Test BetaAppClipInvocationLocalization
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetaAppClipInvocationLocalization`
        """
        model = BetaAppClipInvocationLocalization()
        if include_optional:
            return BetaAppClipInvocationLocalization(
                type = 'betaAppClipInvocationLocalizations',
                id = '',
                attributes = openapi_client.models.beta_app_clip_invocation_localization_attributes.BetaAppClipInvocationLocalization_attributes(
                    title = '', 
                    locale = '', ),
                links = openapi_client.models.resource_links.ResourceLinks(
                    self = '', )
            )
        else:
            return BetaAppClipInvocationLocalization(
                type = 'betaAppClipInvocationLocalizations',
                id = '',
        )
        """

    def testBetaAppClipInvocationLocalization(self):
        """Test BetaAppClipInvocationLocalization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
