# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.beta_public_link_usages_v1_metric_response_data_inner_data_points import BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints

class TestBetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints(unittest.TestCase):
    """BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints:
        """Test BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints`
        """
        model = BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints()
        if include_optional:
            return BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints(
                start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                values = openapi_client.models.beta_public_link_usages_v1_metric_response_data_inner_data_points_values.BetaPublicLinkUsagesV1MetricResponse_data_inner_dataPoints_values(
                    view_count = 56, 
                    accepted_count = 56, 
                    did_not_accept_count = 56, 
                    did_not_meet_criteria_count = 56, 
                    not_relevant_ratio = 1.337, 
                    not_clear_ratio = 1.337, 
                    not_interesting_ratio = 1.337, )
            )
        else:
            return BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints(
        )
        """

    def testBetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints(self):
        """Test BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
