# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_price_schedule_create_request import AppPriceScheduleCreateRequest

class TestAppPriceScheduleCreateRequest(unittest.TestCase):
    """AppPriceScheduleCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppPriceScheduleCreateRequest:
        """Test AppPriceScheduleCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppPriceScheduleCreateRequest`
        """
        model = AppPriceScheduleCreateRequest()
        if include_optional:
            return AppPriceScheduleCreateRequest(
                data = openapi_client.models.app_price_schedule_create_request_data.AppPriceScheduleCreateRequest_data(
                    type = 'appPriceSchedules', 
                    relationships = openapi_client.models.app_price_schedule_create_request_data_relationships.AppPriceScheduleCreateRequest_data_relationships(
                        app = openapi_client.models.accessibility_declaration_create_request_data_relationships_app.AccessibilityDeclarationCreateRequest_data_relationships_app(
                            data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                                type = 'apps', 
                                id = '', ), ), 
                        base_territory = openapi_client.models.app_price_schedule_create_request_data_relationships_base_territory.AppPriceScheduleCreateRequest_data_relationships_baseTerritory(
                            data = openapi_client.models.app_price_point_v3_relationships_territory_data.AppPricePointV3_relationships_territory_data(
                                type = 'territories', 
                                id = '', ), ), 
                        manual_prices = openapi_client.models.app_price_schedule_create_request_data_relationships_manual_prices.AppPriceScheduleCreateRequest_data_relationships_manualPrices(
                            data = [
                                openapi_client.models.app_price_schedule_relationships_manual_prices_data_inner.AppPriceSchedule_relationships_manualPrices_data_inner(
                                    type = 'appPrices', 
                                    id = '', )
                                ], ), ), ),
                included = [
                    null
                    ]
            )
        else:
            return AppPriceScheduleCreateRequest(
                data = openapi_client.models.app_price_schedule_create_request_data.AppPriceScheduleCreateRequest_data(
                    type = 'appPriceSchedules', 
                    relationships = openapi_client.models.app_price_schedule_create_request_data_relationships.AppPriceScheduleCreateRequest_data_relationships(
                        app = openapi_client.models.accessibility_declaration_create_request_data_relationships_app.AccessibilityDeclarationCreateRequest_data_relationships_app(
                            data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                                type = 'apps', 
                                id = '', ), ), 
                        base_territory = openapi_client.models.app_price_schedule_create_request_data_relationships_base_territory.AppPriceScheduleCreateRequest_data_relationships_baseTerritory(
                            data = openapi_client.models.app_price_point_v3_relationships_territory_data.AppPricePointV3_relationships_territory_data(
                                type = 'territories', 
                                id = '', ), ), 
                        manual_prices = openapi_client.models.app_price_schedule_create_request_data_relationships_manual_prices.AppPriceScheduleCreateRequest_data_relationships_manualPrices(
                            data = [
                                openapi_client.models.app_price_schedule_relationships_manual_prices_data_inner.AppPriceSchedule_relationships_manualPrices_data_inner(
                                    type = 'appPrices', 
                                    id = '', )
                                ], ), ), ),
        )
        """

    def testAppPriceScheduleCreateRequest(self):
        """Test AppPriceScheduleCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
