# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_category_parent_linkage_response import AppCategoryParentLinkageResponse

class TestAppCategoryParentLinkageResponse(unittest.TestCase):
    """AppCategoryParentLinkageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppCategoryParentLinkageResponse:
        """Test AppCategoryParentLinkageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppCategoryParentLinkageResponse`
        """
        model = AppCategoryParentLinkageResponse()
        if include_optional:
            return AppCategoryParentLinkageResponse(
                data = openapi_client.models.app_category_relationships_subcategories_data_inner.AppCategory_relationships_subcategories_data_inner(
                    type = 'appCategories', 
                    id = '', ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', )
            )
        else:
            return AppCategoryParentLinkageResponse(
                data = openapi_client.models.app_category_relationships_subcategories_data_inner.AppCategory_relationships_subcategories_data_inner(
                    type = 'appCategories', 
                    id = '', ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', ),
        )
        """

    def testAppCategoryParentLinkageResponse(self):
        """Test AppCategoryParentLinkageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
