# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.subscription_offer_code_one_time_use_codes_api import SubscriptionOfferCodeOneTimeUseCodesApi


class TestSubscriptionOfferCodeOneTimeUseCodesApi(unittest.TestCase):
    """SubscriptionOfferCodeOneTimeUseCodesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionOfferCodeOneTimeUseCodesApi()

    def tearDown(self) -> None:
        pass

    def test_subscription_offer_code_one_time_use_codes_create_instance(self) -> None:
        """Test case for subscription_offer_code_one_time_use_codes_create_instance

        """
        pass

    def test_subscription_offer_code_one_time_use_codes_get_instance(self) -> None:
        """Test case for subscription_offer_code_one_time_use_codes_get_instance

        """
        pass

    def test_subscription_offer_code_one_time_use_codes_update_instance(self) -> None:
        """Test case for subscription_offer_code_one_time_use_codes_update_instance

        """
        pass

    def test_subscription_offer_code_one_time_use_codes_values_get_to_one_related(self) -> None:
        """Test case for subscription_offer_code_one_time_use_codes_values_get_to_one_related

        """
        pass


if __name__ == '__main__':
    unittest.main()
