# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_availability_v2_create_request_data import AppAvailabilityV2CreateRequestData

class TestAppAvailabilityV2CreateRequestData(unittest.TestCase):
    """AppAvailabilityV2CreateRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppAvailabilityV2CreateRequestData:
        """Test AppAvailabilityV2CreateRequestData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppAvailabilityV2CreateRequestData`
        """
        model = AppAvailabilityV2CreateRequestData()
        if include_optional:
            return AppAvailabilityV2CreateRequestData(
                type = 'appAvailabilities',
                attributes = openapi_client.models.app_availability_v2_create_request_data_attributes.AppAvailabilityV2CreateRequest_data_attributes(
                    available_in_new_territories = True, ),
                relationships = openapi_client.models.app_availability_v2_create_request_data_relationships.AppAvailabilityV2CreateRequest_data_relationships(
                    app = openapi_client.models.accessibility_declaration_create_request_data_relationships_app.AccessibilityDeclarationCreateRequest_data_relationships_app(
                        data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                            type = 'apps', 
                            id = '', ), ), 
                    territory_availabilities = openapi_client.models.app_availability_v2_create_request_data_relationships_territory_availabilities.AppAvailabilityV2CreateRequest_data_relationships_territoryAvailabilities(
                        data = [
                            openapi_client.models.app_availability_v2_relationships_territory_availabilities_data_inner.AppAvailabilityV2_relationships_territoryAvailabilities_data_inner(
                                type = 'territoryAvailabilities', 
                                id = '', )
                            ], ), )
            )
        else:
            return AppAvailabilityV2CreateRequestData(
                type = 'appAvailabilities',
                attributes = openapi_client.models.app_availability_v2_create_request_data_attributes.AppAvailabilityV2CreateRequest_data_attributes(
                    available_in_new_territories = True, ),
                relationships = openapi_client.models.app_availability_v2_create_request_data_relationships.AppAvailabilityV2CreateRequest_data_relationships(
                    app = openapi_client.models.accessibility_declaration_create_request_data_relationships_app.AccessibilityDeclarationCreateRequest_data_relationships_app(
                        data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                            type = 'apps', 
                            id = '', ), ), 
                    territory_availabilities = openapi_client.models.app_availability_v2_create_request_data_relationships_territory_availabilities.AppAvailabilityV2CreateRequest_data_relationships_territoryAvailabilities(
                        data = [
                            openapi_client.models.app_availability_v2_relationships_territory_availabilities_data_inner.AppAvailabilityV2_relationships_territoryAvailabilities_data_inner(
                                type = 'territoryAvailabilities', 
                                id = '', )
                            ], ), ),
        )
        """

    def testAppAvailabilityV2CreateRequestData(self):
        """Test AppAvailabilityV2CreateRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
