# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_matchmaking_rule_response import GameCenterMatchmakingRuleResponse

class TestGameCenterMatchmakingRuleResponse(unittest.TestCase):
    """GameCenterMatchmakingRuleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterMatchmakingRuleResponse:
        """Test GameCenterMatchmakingRuleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterMatchmakingRuleResponse`
        """
        model = GameCenterMatchmakingRuleResponse()
        if include_optional:
            return GameCenterMatchmakingRuleResponse(
                data = openapi_client.models.game_center_matchmaking_rule.GameCenterMatchmakingRule(
                    type = 'gameCenterMatchmakingRules', 
                    id = '', 
                    attributes = openapi_client.models.game_center_matchmaking_rule_attributes.GameCenterMatchmakingRule_attributes(
                        reference_name = '', 
                        description = '', 
                        type = 'COMPATIBLE', 
                        expression = '', 
                        weight = 1.337, ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', )
            )
        else:
            return GameCenterMatchmakingRuleResponse(
                data = openapi_client.models.game_center_matchmaking_rule.GameCenterMatchmakingRule(
                    type = 'gameCenterMatchmakingRules', 
                    id = '', 
                    attributes = openapi_client.models.game_center_matchmaking_rule_attributes.GameCenterMatchmakingRule_attributes(
                        reference_name = '', 
                        description = '', 
                        type = 'COMPATIBLE', 
                        expression = '', 
                        weight = 1.337, ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', ),
        )
        """

    def testGameCenterMatchmakingRuleResponse(self):
        """Test GameCenterMatchmakingRuleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
