# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.win_back_offer_price import WinBackOfferPrice

class TestWinBackOfferPrice(unittest.TestCase):
    """WinBackOfferPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WinBackOfferPrice:
        """Test WinBackOfferPrice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WinBackOfferPrice`
        """
        model = WinBackOfferPrice()
        if include_optional:
            return WinBackOfferPrice(
                type = 'winBackOfferPrices',
                id = '',
                relationships = openapi_client.models.subscription_offer_code_price_relationships.SubscriptionOfferCodePrice_relationships(
                    territory = openapi_client.models.app_price_point_v3_relationships_territory.AppPricePointV3_relationships_territory(
                        data = openapi_client.models.app_price_point_v3_relationships_territory_data.AppPricePointV3_relationships_territory_data(
                            type = 'territories', 
                            id = '', ), ), 
                    subscription_price_point = openapi_client.models.subscription_introductory_offer_relationships_subscription_price_point.SubscriptionIntroductoryOffer_relationships_subscriptionPricePoint(), ),
                links = openapi_client.models.resource_links.ResourceLinks(
                    self = '', )
            )
        else:
            return WinBackOfferPrice(
                type = 'winBackOfferPrices',
                id = '',
        )
        """

    def testWinBackOfferPrice(self):
        """Test WinBackOfferPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
