# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_leaderboard_image_response import GameCenterLeaderboardImageResponse

class TestGameCenterLeaderboardImageResponse(unittest.TestCase):
    """GameCenterLeaderboardImageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterLeaderboardImageResponse:
        """Test GameCenterLeaderboardImageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterLeaderboardImageResponse`
        """
        model = GameCenterLeaderboardImageResponse()
        if include_optional:
            return GameCenterLeaderboardImageResponse(
                data = openapi_client.models.game_center_leaderboard_image.GameCenterLeaderboardImage(
                    type = 'gameCenterLeaderboardImages', 
                    id = '', 
                    attributes = openapi_client.models.game_center_achievement_image_attributes.GameCenterAchievementImage_attributes(
                        file_size = 56, 
                        file_name = '', 
                        image_asset = openapi_client.models.image_asset.ImageAsset(
                            template_url = '', 
                            width = 56, 
                            height = 56, ), 
                        upload_operations = [
                            openapi_client.models.upload_operation.UploadOperation(
                                method = '', 
                                url = '', 
                                length = 56, 
                                offset = 56, 
                                request_headers = [
                                    openapi_client.models.http_header.HttpHeader(
                                        name = '', 
                                        value = '', )
                                    ], )
                            ], 
                        asset_delivery_state = openapi_client.models.app_media_asset_state.AppMediaAssetState(
                            errors = [
                                openapi_client.models.app_media_state_error.AppMediaStateError(
                                    code = '', 
                                    description = '', )
                                ], 
                            warnings = [
                                openapi_client.models.app_media_state_error.AppMediaStateError(
                                    code = '', 
                                    description = '', )
                                ], 
                            state = 'AWAITING_UPLOAD', ), ), 
                    relationships = openapi_client.models.game_center_leaderboard_image_relationships.GameCenterLeaderboardImage_relationships(
                        game_center_leaderboard_localization = openapi_client.models.game_center_leaderboard_image_relationships_game_center_leaderboard_localization.GameCenterLeaderboardImage_relationships_gameCenterLeaderboardLocalization(
                            data = openapi_client.models.game_center_leaderboard_image_relationships_game_center_leaderboard_localization_data.GameCenterLeaderboardImage_relationships_gameCenterLeaderboardLocalization_data(
                                type = 'gameCenterLeaderboardLocalizations', 
                                id = '', ), ), ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                included = [
                    openapi_client.models.game_center_leaderboard_localization.GameCenterLeaderboardLocalization(
                        type = 'gameCenterLeaderboardLocalizations', 
                        id = '', 
                        attributes = openapi_client.models.game_center_leaderboard_localization_attributes.GameCenterLeaderboardLocalization_attributes(
                            locale = '', 
                            name = '', 
                            formatter_override = 'INTEGER', 
                            formatter_suffix = '', 
                            formatter_suffix_singular = '', ), 
                        relationships = openapi_client.models.game_center_leaderboard_localization_relationships.GameCenterLeaderboardLocalization_relationships(
                            game_center_leaderboard = openapi_client.models.game_center_challenge_create_request_data_relationships_leaderboard.GameCenterChallengeCreateRequest_data_relationships_leaderboard(
                                data = openapi_client.models.game_center_activity_relationships_leaderboards_data_inner.GameCenterActivity_relationships_leaderboards_data_inner(
                                    type = 'gameCenterLeaderboards', 
                                    id = '', ), ), 
                            game_center_leaderboard_image = openapi_client.models.game_center_leaderboard_localization_relationships_game_center_leaderboard_image.GameCenterLeaderboardLocalization_relationships_gameCenterLeaderboardImage(
                                links = openapi_client.models.relationship_links.RelationshipLinks(
                                    self = '', 
                                    related = '', ), ), ), 
                        links = openapi_client.models.resource_links.ResourceLinks(
                            self = '', ), )
                    ],
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', )
            )
        else:
            return GameCenterLeaderboardImageResponse(
                data = openapi_client.models.game_center_leaderboard_image.GameCenterLeaderboardImage(
                    type = 'gameCenterLeaderboardImages', 
                    id = '', 
                    attributes = openapi_client.models.game_center_achievement_image_attributes.GameCenterAchievementImage_attributes(
                        file_size = 56, 
                        file_name = '', 
                        image_asset = openapi_client.models.image_asset.ImageAsset(
                            template_url = '', 
                            width = 56, 
                            height = 56, ), 
                        upload_operations = [
                            openapi_client.models.upload_operation.UploadOperation(
                                method = '', 
                                url = '', 
                                length = 56, 
                                offset = 56, 
                                request_headers = [
                                    openapi_client.models.http_header.HttpHeader(
                                        name = '', 
                                        value = '', )
                                    ], )
                            ], 
                        asset_delivery_state = openapi_client.models.app_media_asset_state.AppMediaAssetState(
                            errors = [
                                openapi_client.models.app_media_state_error.AppMediaStateError(
                                    code = '', 
                                    description = '', )
                                ], 
                            warnings = [
                                openapi_client.models.app_media_state_error.AppMediaStateError(
                                    code = '', 
                                    description = '', )
                                ], 
                            state = 'AWAITING_UPLOAD', ), ), 
                    relationships = openapi_client.models.game_center_leaderboard_image_relationships.GameCenterLeaderboardImage_relationships(
                        game_center_leaderboard_localization = openapi_client.models.game_center_leaderboard_image_relationships_game_center_leaderboard_localization.GameCenterLeaderboardImage_relationships_gameCenterLeaderboardLocalization(
                            data = openapi_client.models.game_center_leaderboard_image_relationships_game_center_leaderboard_localization_data.GameCenterLeaderboardImage_relationships_gameCenterLeaderboardLocalization_data(
                                type = 'gameCenterLeaderboardLocalizations', 
                                id = '', ), ), ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', ),
        )
        """

    def testGameCenterLeaderboardImageResponse(self):
        """Test GameCenterLeaderboardImageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
