# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscription_group_localization_attributes import SubscriptionGroupLocalizationAttributes

class TestSubscriptionGroupLocalizationAttributes(unittest.TestCase):
    """SubscriptionGroupLocalizationAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionGroupLocalizationAttributes:
        """Test SubscriptionGroupLocalizationAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionGroupLocalizationAttributes`
        """
        model = SubscriptionGroupLocalizationAttributes()
        if include_optional:
            return SubscriptionGroupLocalizationAttributes(
                name = '',
                custom_app_name = '',
                locale = '',
                state = 'PREPARE_FOR_SUBMISSION'
            )
        else:
            return SubscriptionGroupLocalizationAttributes(
        )
        """

    def testSubscriptionGroupLocalizationAttributes(self):
        """Test SubscriptionGroupLocalizationAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
