# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_clip_app_store_review_detail_update_request import AppClipAppStoreReviewDetailUpdateRequest

class TestAppClipAppStoreReviewDetailUpdateRequest(unittest.TestCase):
    """AppClipAppStoreReviewDetailUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppClipAppStoreReviewDetailUpdateRequest:
        """Test AppClipAppStoreReviewDetailUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppClipAppStoreReviewDetailUpdateRequest`
        """
        model = AppClipAppStoreReviewDetailUpdateRequest()
        if include_optional:
            return AppClipAppStoreReviewDetailUpdateRequest(
                data = openapi_client.models.app_clip_app_store_review_detail_update_request_data.AppClipAppStoreReviewDetailUpdateRequest_data(
                    type = 'appClipAppStoreReviewDetails', 
                    id = '', 
                    attributes = openapi_client.models.app_clip_app_store_review_detail_attributes.AppClipAppStoreReviewDetail_attributes(
                        invocation_urls = [
                            ''
                            ], ), )
            )
        else:
            return AppClipAppStoreReviewDetailUpdateRequest(
                data = openapi_client.models.app_clip_app_store_review_detail_update_request_data.AppClipAppStoreReviewDetailUpdateRequest_data(
                    type = 'appClipAppStoreReviewDetails', 
                    id = '', 
                    attributes = openapi_client.models.app_clip_app_store_review_detail_attributes.AppClipAppStoreReviewDetail_attributes(
                        invocation_urls = [
                            ''
                            ], ), ),
        )
        """

    def testAppClipAppStoreReviewDetailUpdateRequest(self):
        """Test AppClipAppStoreReviewDetailUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
