# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_review_response_v1_create_request_data_relationships import CustomerReviewResponseV1CreateRequestDataRelationships

class TestCustomerReviewResponseV1CreateRequestDataRelationships(unittest.TestCase):
    """CustomerReviewResponseV1CreateRequestDataRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerReviewResponseV1CreateRequestDataRelationships:
        """Test CustomerReviewResponseV1CreateRequestDataRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerReviewResponseV1CreateRequestDataRelationships`
        """
        model = CustomerReviewResponseV1CreateRequestDataRelationships()
        if include_optional:
            return CustomerReviewResponseV1CreateRequestDataRelationships(
                review = openapi_client.models.customer_review_response_v1_create_request_data_relationships_review.CustomerReviewResponseV1CreateRequest_data_relationships_review(
                    data = openapi_client.models.customer_review_response_v1_relationships_review_data.CustomerReviewResponseV1_relationships_review_data(
                        type = 'customerReviews', 
                        id = '', ), )
            )
        else:
            return CustomerReviewResponseV1CreateRequestDataRelationships(
                review = openapi_client.models.customer_review_response_v1_create_request_data_relationships_review.CustomerReviewResponseV1CreateRequest_data_relationships_review(
                    data = openapi_client.models.customer_review_response_v1_relationships_review_data.CustomerReviewResponseV1_relationships_review_data(
                        type = 'customerReviews', 
                        id = '', ), ),
        )
        """

    def testCustomerReviewResponseV1CreateRequestDataRelationships(self):
        """Test CustomerReviewResponseV1CreateRequestDataRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
