# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_leaderboard_create_request_data import GameCenterLeaderboardCreateRequestData

class TestGameCenterLeaderboardCreateRequestData(unittest.TestCase):
    """GameCenterLeaderboardCreateRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterLeaderboardCreateRequestData:
        """Test GameCenterLeaderboardCreateRequestData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterLeaderboardCreateRequestData`
        """
        model = GameCenterLeaderboardCreateRequestData()
        if include_optional:
            return GameCenterLeaderboardCreateRequestData(
                type = 'gameCenterLeaderboards',
                attributes = openapi_client.models.game_center_leaderboard_create_request_data_attributes.GameCenterLeaderboardCreateRequest_data_attributes(
                    default_formatter = 'INTEGER', 
                    reference_name = '', 
                    vendor_identifier = '', 
                    submission_type = 'BEST_SCORE', 
                    score_sort_type = 'ASC', 
                    score_range_start = 1, 
                    score_range_end = 1, 
                    recurrence_start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    recurrence_duration = '', 
                    recurrence_rule = '', 
                    activity_properties = {
                        'key' : ''
                        }, 
                    visibility = 'SHOW_FOR_ALL', ),
                relationships = openapi_client.models.game_center_leaderboard_create_request_data_relationships.GameCenterLeaderboardCreateRequest_data_relationships(
                    game_center_detail = openapi_client.models.game_center_achievement_release_relationships_game_center_detail.GameCenterAchievementRelease_relationships_gameCenterDetail(
                        data = openapi_client.models.app_relationships_game_center_detail_data.App_relationships_gameCenterDetail_data(
                            type = 'gameCenterDetails', 
                            id = '', ), ), 
                    game_center_group = openapi_client.models.game_center_achievement_relationships_game_center_group.GameCenterAchievement_relationships_gameCenterGroup(), 
                    game_center_leaderboard_sets = openapi_client.models.game_center_leaderboard_create_request_data_relationships_game_center_leaderboard_sets.GameCenterLeaderboardCreateRequest_data_relationships_gameCenterLeaderboardSets(), )
            )
        else:
            return GameCenterLeaderboardCreateRequestData(
                type = 'gameCenterLeaderboards',
                attributes = openapi_client.models.game_center_leaderboard_create_request_data_attributes.GameCenterLeaderboardCreateRequest_data_attributes(
                    default_formatter = 'INTEGER', 
                    reference_name = '', 
                    vendor_identifier = '', 
                    submission_type = 'BEST_SCORE', 
                    score_sort_type = 'ASC', 
                    score_range_start = 1, 
                    score_range_end = 1, 
                    recurrence_start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    recurrence_duration = '', 
                    recurrence_rule = '', 
                    activity_properties = {
                        'key' : ''
                        }, 
                    visibility = 'SHOW_FOR_ALL', ),
        )
        """

    def testGameCenterLeaderboardCreateRequestData(self):
        """Test GameCenterLeaderboardCreateRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
