# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_challenge_localization_create_request import GameCenterChallengeLocalizationCreateRequest

class TestGameCenterChallengeLocalizationCreateRequest(unittest.TestCase):
    """GameCenterChallengeLocalizationCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterChallengeLocalizationCreateRequest:
        """Test GameCenterChallengeLocalizationCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterChallengeLocalizationCreateRequest`
        """
        model = GameCenterChallengeLocalizationCreateRequest()
        if include_optional:
            return GameCenterChallengeLocalizationCreateRequest(
                data = openapi_client.models.game_center_challenge_localization_create_request_data.GameCenterChallengeLocalizationCreateRequest_data(
                    type = 'gameCenterChallengeLocalizations', 
                    attributes = openapi_client.models.game_center_activity_localization_create_request_data_attributes.GameCenterActivityLocalizationCreateRequest_data_attributes(
                        locale = '', 
                        name = '', 
                        description = '', ), 
                    relationships = openapi_client.models.game_center_challenge_localization_create_request_data_relationships.GameCenterChallengeLocalizationCreateRequest_data_relationships(
                        version = openapi_client.models.game_center_challenge_localization_create_request_data_relationships_version.GameCenterChallengeLocalizationCreateRequest_data_relationships_version(
                            data = openapi_client.models.game_center_challenge_image_create_request_data_relationships_version_data.GameCenterChallengeImageCreateRequest_data_relationships_version_data(
                                type = 'gameCenterChallengeVersions', 
                                id = '', ), ), ), )
            )
        else:
            return GameCenterChallengeLocalizationCreateRequest(
                data = openapi_client.models.game_center_challenge_localization_create_request_data.GameCenterChallengeLocalizationCreateRequest_data(
                    type = 'gameCenterChallengeLocalizations', 
                    attributes = openapi_client.models.game_center_activity_localization_create_request_data_attributes.GameCenterActivityLocalizationCreateRequest_data_attributes(
                        locale = '', 
                        name = '', 
                        description = '', ), 
                    relationships = openapi_client.models.game_center_challenge_localization_create_request_data_relationships.GameCenterChallengeLocalizationCreateRequest_data_relationships(
                        version = openapi_client.models.game_center_challenge_localization_create_request_data_relationships_version.GameCenterChallengeLocalizationCreateRequest_data_relationships_version(
                            data = openapi_client.models.game_center_challenge_image_create_request_data_relationships_version_data.GameCenterChallengeImageCreateRequest_data_relationships_version_data(
                                type = 'gameCenterChallengeVersions', 
                                id = '', ), ), ), ),
        )
        """

    def testGameCenterChallengeLocalizationCreateRequest(self):
        """Test GameCenterChallengeLocalizationCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
