# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscription_relationships_subscription_availability import SubscriptionRelationshipsSubscriptionAvailability

class TestSubscriptionRelationshipsSubscriptionAvailability(unittest.TestCase):
    """SubscriptionRelationshipsSubscriptionAvailability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionRelationshipsSubscriptionAvailability:
        """Test SubscriptionRelationshipsSubscriptionAvailability
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionRelationshipsSubscriptionAvailability`
        """
        model = SubscriptionRelationshipsSubscriptionAvailability()
        if include_optional:
            return SubscriptionRelationshipsSubscriptionAvailability(
                links = openapi_client.models.relationship_links.RelationshipLinks(
                    self = '', 
                    related = '', ),
                data = openapi_client.models.subscription_relationships_subscription_availability_data.Subscription_relationships_subscriptionAvailability_data(
                    type = 'subscriptionAvailabilities', 
                    id = '', )
            )
        else:
            return SubscriptionRelationshipsSubscriptionAvailability(
        )
        """

    def testSubscriptionRelationshipsSubscriptionAvailability(self):
        """Test SubscriptionRelationshipsSubscriptionAvailability"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
