# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.build_bundle_file_size_attributes import BuildBundleFileSizeAttributes

class TestBuildBundleFileSizeAttributes(unittest.TestCase):
    """BuildBundleFileSizeAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuildBundleFileSizeAttributes:
        """Test BuildBundleFileSizeAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuildBundleFileSizeAttributes`
        """
        model = BuildBundleFileSizeAttributes()
        if include_optional:
            return BuildBundleFileSizeAttributes(
                device_model = '',
                os_version = '',
                download_bytes = 56,
                install_bytes = 56
            )
        else:
            return BuildBundleFileSizeAttributes(
        )
        """

    def testBuildBundleFileSizeAttributes(self):
        """Test BuildBundleFileSizeAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
