# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.beta_crash_logs_api import BetaCrashLogsApi


class TestBetaCrashLogsApi(unittest.TestCase):
    """BetaCrashLogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BetaCrashLogsApi()

    def tearDown(self) -> None:
        pass

    def test_beta_crash_logs_get_instance(self) -> None:
        """Test case for beta_crash_logs_get_instance

        """
        pass


if __name__ == '__main__':
    unittest.main()
