# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_detail_relationships_game_center_activities import GameCenterDetailRelationshipsGameCenterActivities

class TestGameCenterDetailRelationshipsGameCenterActivities(unittest.TestCase):
    """GameCenterDetailRelationshipsGameCenterActivities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterDetailRelationshipsGameCenterActivities:
        """Test GameCenterDetailRelationshipsGameCenterActivities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterDetailRelationshipsGameCenterActivities`
        """
        model = GameCenterDetailRelationshipsGameCenterActivities()
        if include_optional:
            return GameCenterDetailRelationshipsGameCenterActivities(
                links = openapi_client.models.relationship_links.RelationshipLinks(
                    self = '', 
                    related = '', ),
                meta = openapi_client.models.paging_information.PagingInformation(
                    paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                        total = 56, 
                        limit = 56, 
                        next_cursor = '', ), ),
                data = [
                    openapi_client.models.game_center_achievement_relationships_activity_data.GameCenterAchievement_relationships_activity_data(
                        type = 'gameCenterActivities', 
                        id = '', )
                    ]
            )
        else:
            return GameCenterDetailRelationshipsGameCenterActivities(
        )
        """

    def testGameCenterDetailRelationshipsGameCenterActivities(self):
        """Test GameCenterDetailRelationshipsGameCenterActivities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
