# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_store_version_relationships import AppStoreVersionRelationships

class TestAppStoreVersionRelationships(unittest.TestCase):
    """AppStoreVersionRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppStoreVersionRelationships:
        """Test AppStoreVersionRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppStoreVersionRelationships`
        """
        model = AppStoreVersionRelationships()
        if include_optional:
            return AppStoreVersionRelationships(
                app = openapi_client.models.alternative_distribution_key_create_request_data_relationships_app.AlternativeDistributionKeyCreateRequest_data_relationships_app(
                    data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                        type = 'apps', 
                        id = '', ), ),
                age_rating_declaration = openapi_client.models.app_store_version_relationships_age_rating_declaration.AppStoreVersion_relationships_ageRatingDeclaration(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.app_info_relationships_age_rating_declaration_data.AppInfo_relationships_ageRatingDeclaration_data(
                        type = 'ageRatingDeclarations', 
                        id = '', ), ),
                app_store_version_localizations = openapi_client.models.app_store_version_relationships_app_store_version_localizations.AppStoreVersion_relationships_appStoreVersionLocalizations(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.app_preview_set_relationships_app_store_version_localization_data.AppPreviewSet_relationships_appStoreVersionLocalization_data(
                            type = 'appStoreVersionLocalizations', 
                            id = '', )
                        ], ),
                build = openapi_client.models.app_store_version_relationships_build.AppStoreVersion_relationships_build(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.app_encryption_declaration_relationships_builds_data_inner.AppEncryptionDeclaration_relationships_builds_data_inner(
                        type = 'builds', 
                        id = '', ), ),
                app_store_version_phased_release = openapi_client.models.app_store_version_relationships_app_store_version_phased_release.AppStoreVersion_relationships_appStoreVersionPhasedRelease(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.app_store_version_relationships_app_store_version_phased_release_data.AppStoreVersion_relationships_appStoreVersionPhasedRelease_data(
                        type = 'appStoreVersionPhasedReleases', 
                        id = '', ), ),
                game_center_app_version = openapi_client.models.app_store_version_relationships_game_center_app_version.AppStoreVersion_relationships_gameCenterAppVersion(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.app_store_version_relationships_game_center_app_version_data.AppStoreVersion_relationships_gameCenterAppVersion_data(
                        type = 'gameCenterAppVersions', 
                        id = '', ), ),
                routing_app_coverage = openapi_client.models.app_store_version_relationships_routing_app_coverage.AppStoreVersion_relationships_routingAppCoverage(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.app_store_version_relationships_routing_app_coverage_data.AppStoreVersion_relationships_routingAppCoverage_data(
                        type = 'routingAppCoverages', 
                        id = '', ), ),
                app_store_review_detail = openapi_client.models.app_store_version_relationships_app_store_review_detail.AppStoreVersion_relationships_appStoreReviewDetail(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.app_store_review_attachment_relationships_app_store_review_detail_data.AppStoreReviewAttachment_relationships_appStoreReviewDetail_data(
                        type = 'appStoreReviewDetails', 
                        id = '', ), ),
                app_store_version_submission = openapi_client.models.app_store_version_relationships_app_store_version_submission.AppStoreVersion_relationships_appStoreVersionSubmission(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.app_store_version_relationships_app_store_version_submission_data.AppStoreVersion_relationships_appStoreVersionSubmission_data(
                        type = 'appStoreVersionSubmissions', 
                        id = '', ), ),
                app_clip_default_experience = openapi_client.models.app_store_version_relationships_app_clip_default_experience.AppStoreVersion_relationships_appClipDefaultExperience(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.app_clip_app_store_review_detail_relationships_app_clip_default_experience_data.AppClipAppStoreReviewDetail_relationships_appClipDefaultExperience_data(
                        type = 'appClipDefaultExperiences', 
                        id = '', ), ),
                app_store_version_experiments = openapi_client.models.app_store_version_relationships_app_store_version_experiments.AppStoreVersion_relationships_appStoreVersionExperiments(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.app_store_version_experiment_treatment_relationships_app_store_version_experiment_data.AppStoreVersionExperimentTreatment_relationships_appStoreVersionExperiment_data(
                            type = 'appStoreVersionExperiments', 
                            id = '', )
                        ], ),
                app_store_version_experiments_v2 = openapi_client.models.app_store_version_relationships_app_store_version_experiments.AppStoreVersion_relationships_appStoreVersionExperiments(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.app_store_version_experiment_treatment_relationships_app_store_version_experiment_data.AppStoreVersionExperimentTreatment_relationships_appStoreVersionExperiment_data(
                            type = 'appStoreVersionExperiments', 
                            id = '', )
                        ], ),
                customer_reviews = openapi_client.models.analytics_report_instance_relationships_segments.AnalyticsReportInstance_relationships_segments(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), ),
                alternative_distribution_package = openapi_client.models.app_store_version_relationships_alternative_distribution_package.AppStoreVersion_relationships_alternativeDistributionPackage(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.alternative_distribution_package_version_relationships_alternative_distribution_package_data.AlternativeDistributionPackageVersion_relationships_alternativeDistributionPackage_data(
                        type = 'alternativeDistributionPackages', 
                        id = '', ), )
            )
        else:
            return AppStoreVersionRelationships(
        )
        """

    def testAppStoreVersionRelationships(self):
        """Test AppStoreVersionRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
