# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ci_action import CiAction

class TestCiAction(unittest.TestCase):
    """CiAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CiAction:
        """Test CiAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CiAction`
        """
        model = CiAction()
        if include_optional:
            return CiAction(
                name = '',
                action_type = 'BUILD',
                destination = 'ANY_IOS_DEVICE',
                build_distribution_audience = 'INTERNAL_ONLY',
                test_configuration = openapi_client.models.ci_action_test_configuration.CiAction_testConfiguration(
                    kind = 'USE_SCHEME_SETTINGS', 
                    test_plan_name = '', 
                    test_destinations = [
                        openapi_client.models.ci_test_destination.CiTestDestination(
                            device_type_name = '', 
                            device_type_identifier = '', 
                            runtime_name = '', 
                            runtime_identifier = '', 
                            kind = 'SIMULATOR', )
                        ], ),
                scheme = '',
                platform = 'MACOS',
                is_required_to_pass = True
            )
        else:
            return CiAction(
        )
        """

    def testCiAction(self):
        """Test CiAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
