# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sandbox_tester_v2_response import SandboxTesterV2Response

class TestSandboxTesterV2Response(unittest.TestCase):
    """SandboxTesterV2Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SandboxTesterV2Response:
        """Test SandboxTesterV2Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SandboxTesterV2Response`
        """
        model = SandboxTesterV2Response()
        if include_optional:
            return SandboxTesterV2Response(
                data = openapi_client.models.sandbox_tester_v2.SandboxTesterV2(
                    type = 'sandboxTesters', 
                    id = '', 
                    attributes = openapi_client.models.sandbox_tester_v2_attributes.SandboxTesterV2_attributes(
                        first_name = '', 
                        last_name = '', 
                        ac_account_name = '', 
                        territory = 'ABW', 
                        apple_pay_compatible = True, 
                        interrupt_purchases = True, 
                        subscription_renewal_rate = 'MONTHLY_RENEWAL_EVERY_ONE_HOUR', ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', )
            )
        else:
            return SandboxTesterV2Response(
                data = openapi_client.models.sandbox_tester_v2.SandboxTesterV2(
                    type = 'sandboxTesters', 
                    id = '', 
                    attributes = openapi_client.models.sandbox_tester_v2_attributes.SandboxTesterV2_attributes(
                        first_name = '', 
                        last_name = '', 
                        ac_account_name = '', 
                        territory = 'ABW', 
                        apple_pay_compatible = True, 
                        interrupt_purchases = True, 
                        subscription_renewal_rate = 'MONTHLY_RENEWAL_EVERY_ONE_HOUR', ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', ),
        )
        """

    def testSandboxTesterV2Response(self):
        """Test SandboxTesterV2Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
