# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscription_promotional_offer_inline_create_relationships import SubscriptionPromotionalOfferInlineCreateRelationships

class TestSubscriptionPromotionalOfferInlineCreateRelationships(unittest.TestCase):
    """SubscriptionPromotionalOfferInlineCreateRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionPromotionalOfferInlineCreateRelationships:
        """Test SubscriptionPromotionalOfferInlineCreateRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionPromotionalOfferInlineCreateRelationships`
        """
        model = SubscriptionPromotionalOfferInlineCreateRelationships()
        if include_optional:
            return SubscriptionPromotionalOfferInlineCreateRelationships(
                subscription = openapi_client.models.promoted_purchase_relationships_subscription.PromotedPurchase_relationships_subscription(
                    data = openapi_client.models.promoted_purchase_relationships_subscription_data.PromotedPurchase_relationships_subscription_data(
                        type = 'subscriptions', 
                        id = '', ), ),
                prices = openapi_client.models.subscription_promotional_offer_inline_create_relationships_prices.SubscriptionPromotionalOfferInlineCreate_relationships_prices(
                    data = [
                        openapi_client.models.subscription_promotional_offer_relationships_prices_data_inner.SubscriptionPromotionalOffer_relationships_prices_data_inner(
                            type = 'subscriptionPromotionalOfferPrices', 
                            id = '', )
                        ], )
            )
        else:
            return SubscriptionPromotionalOfferInlineCreateRelationships(
        )
        """

    def testSubscriptionPromotionalOfferInlineCreateRelationships(self):
        """Test SubscriptionPromotionalOfferInlineCreateRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
