# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_price_schedule_create_request_data_relationships_base_territory import AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory

class TestAppPriceScheduleCreateRequestDataRelationshipsBaseTerritory(unittest.TestCase):
    """AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory:
        """Test AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory`
        """
        model = AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory()
        if include_optional:
            return AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory(
                data = openapi_client.models.app_price_point_v3_relationships_territory_data.AppPricePointV3_relationships_territory_data(
                    type = 'territories', 
                    id = '', )
            )
        else:
            return AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory(
                data = openapi_client.models.app_price_point_v3_relationships_territory_data.AppPricePointV3_relationships_territory_data(
                    type = 'territories', 
                    id = '', ),
        )
        """

    def testAppPriceScheduleCreateRequestDataRelationshipsBaseTerritory(self):
        """Test AppPriceScheduleCreateRequestDataRelationshipsBaseTerritory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
