# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scm_provider_type import ScmProviderType

class TestScmProviderType(unittest.TestCase):
    """ScmProviderType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScmProviderType:
        """Test ScmProviderType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScmProviderType`
        """
        model = ScmProviderType()
        if include_optional:
            return ScmProviderType(
                kind = 'BITBUCKET_CLOUD',
                display_name = '',
                is_on_premise = True
            )
        else:
            return ScmProviderType(
        )
        """

    def testScmProviderType(self):
        """Test ScmProviderType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
