# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_encryption_declaration_relationships_app_encryption_declaration_document_data import AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData

class TestAppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData(unittest.TestCase):
    """AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData:
        """Test AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData`
        """
        model = AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData()
        if include_optional:
            return AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData(
                type = 'appEncryptionDeclarationDocuments',
                id = ''
            )
        else:
            return AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData(
                type = 'appEncryptionDeclarationDocuments',
                id = '',
        )
        """

    def testAppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData(self):
        """Test AppEncryptionDeclarationRelationshipsAppEncryptionDeclarationDocumentData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
