# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_enabled_version_relationships import GameCenterEnabledVersionRelationships

class TestGameCenterEnabledVersionRelationships(unittest.TestCase):
    """GameCenterEnabledVersionRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterEnabledVersionRelationships:
        """Test GameCenterEnabledVersionRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterEnabledVersionRelationships`
        """
        model = GameCenterEnabledVersionRelationships()
        if include_optional:
            return GameCenterEnabledVersionRelationships(
                compatible_versions = openapi_client.models.app_relationships_game_center_enabled_versions.App_relationships_gameCenterEnabledVersions(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.app_relationships_game_center_enabled_versions_data_inner.App_relationships_gameCenterEnabledVersions_data_inner(
                            type = 'gameCenterEnabledVersions', 
                            id = '', )
                        ], ),
                app = openapi_client.models.alternative_distribution_key_create_request_data_relationships_app.AlternativeDistributionKeyCreateRequest_data_relationships_app(
                    data = openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                        type = 'apps', 
                        id = '', ), )
            )
        else:
            return GameCenterEnabledVersionRelationships(
        )
        """

    def testGameCenterEnabledVersionRelationships(self):
        """Test GameCenterEnabledVersionRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
