# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_visible_apps_linkages_request import UserVisibleAppsLinkagesRequest

class TestUserVisibleAppsLinkagesRequest(unittest.TestCase):
    """UserVisibleAppsLinkagesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserVisibleAppsLinkagesRequest:
        """Test UserVisibleAppsLinkagesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserVisibleAppsLinkagesRequest`
        """
        model = UserVisibleAppsLinkagesRequest()
        if include_optional:
            return UserVisibleAppsLinkagesRequest(
                data = [
                    openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                        type = 'apps', 
                        id = '', )
                    ]
            )
        else:
            return UserVisibleAppsLinkagesRequest(
                data = [
                    openapi_client.models.accessibility_declaration_create_request_data_relationships_app_data.AccessibilityDeclarationCreateRequest_data_relationships_app_data(
                        type = 'apps', 
                        id = '', )
                    ],
        )
        """

    def testUserVisibleAppsLinkagesRequest(self):
        """Test UserVisibleAppsLinkagesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
