# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_matchmaking_team_assignment import GameCenterMatchmakingTeamAssignment

class TestGameCenterMatchmakingTeamAssignment(unittest.TestCase):
    """GameCenterMatchmakingTeamAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterMatchmakingTeamAssignment:
        """Test GameCenterMatchmakingTeamAssignment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterMatchmakingTeamAssignment`
        """
        model = GameCenterMatchmakingTeamAssignment()
        if include_optional:
            return GameCenterMatchmakingTeamAssignment(
                player_id = '',
                team = ''
            )
        else:
            return GameCenterMatchmakingTeamAssignment(
        )
        """

    def testGameCenterMatchmakingTeamAssignment(self):
        """Test GameCenterMatchmakingTeamAssignment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
