# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.background_asset_version_create_request_data_relationships_background_asset import BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset

class TestBackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset(unittest.TestCase):
    """BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset:
        """Test BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset`
        """
        model = BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset()
        if include_optional:
            return BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset(
                data = openapi_client.models.background_asset_version_create_request_data_relationships_background_asset_data.BackgroundAssetVersionCreateRequest_data_relationships_backgroundAsset_data(
                    type = 'backgroundAssets', 
                    id = '', )
            )
        else:
            return BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset(
                data = openapi_client.models.background_asset_version_create_request_data_relationships_background_asset_data.BackgroundAssetVersionCreateRequest_data_relationships_backgroundAsset_data(
                    type = 'backgroundAssets', 
                    id = '', ),
        )
        """

    def testBackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset(self):
        """Test BackgroundAssetVersionCreateRequestDataRelationshipsBackgroundAsset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
