# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ci_pull_request_start_condition import CiPullRequestStartCondition

class TestCiPullRequestStartCondition(unittest.TestCase):
    """CiPullRequestStartCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CiPullRequestStartCondition:
        """Test CiPullRequestStartCondition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CiPullRequestStartCondition`
        """
        model = CiPullRequestStartCondition()
        if include_optional:
            return CiPullRequestStartCondition(
                source = openapi_client.models.ci_branch_patterns.CiBranchPatterns(
                    is_all_match = True, 
                    patterns = [
                        openapi_client.models.ci_branch_patterns_patterns_inner.CiBranchPatterns_patterns_inner(
                            pattern = '', 
                            is_prefix = True, )
                        ], ),
                destination = openapi_client.models.ci_branch_patterns.CiBranchPatterns(
                    is_all_match = True, 
                    patterns = [
                        openapi_client.models.ci_branch_patterns_patterns_inner.CiBranchPatterns_patterns_inner(
                            pattern = '', 
                            is_prefix = True, )
                        ], ),
                files_and_folders_rule = openapi_client.models.ci_files_and_folders_rule.CiFilesAndFoldersRule(
                    mode = 'START_IF_ANY_FILE_MATCHES', 
                    matchers = [
                        openapi_client.models.ci_start_condition_file_matcher.CiStartConditionFileMatcher(
                            directory = '', 
                            file_extension = '', 
                            file_name = '', )
                        ], ),
                auto_cancel = True
            )
        else:
            return CiPullRequestStartCondition(
        )
        """

    def testCiPullRequestStartCondition(self):
        """Test CiPullRequestStartCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
