# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_leaderboard_set_relationships import GameCenterLeaderboardSetRelationships

class TestGameCenterLeaderboardSetRelationships(unittest.TestCase):
    """GameCenterLeaderboardSetRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterLeaderboardSetRelationships:
        """Test GameCenterLeaderboardSetRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterLeaderboardSetRelationships`
        """
        model = GameCenterLeaderboardSetRelationships()
        if include_optional:
            return GameCenterLeaderboardSetRelationships(
                game_center_detail = openapi_client.models.game_center_achievement_release_relationships_game_center_detail.GameCenterAchievementRelease_relationships_gameCenterDetail(
                    data = openapi_client.models.app_relationships_game_center_detail_data.App_relationships_gameCenterDetail_data(
                        type = 'gameCenterDetails', 
                        id = '', ), ),
                game_center_group = openapi_client.models.game_center_achievement_relationships_game_center_group.GameCenterAchievement_relationships_gameCenterGroup(
                    data = openapi_client.models.game_center_achievement_relationships_game_center_group_data.GameCenterAchievement_relationships_gameCenterGroup_data(
                        type = 'gameCenterGroups', 
                        id = '', ), ),
                group_leaderboard_set = openapi_client.models.game_center_leaderboard_set_relationships_group_leaderboard_set.GameCenterLeaderboardSet_relationships_groupLeaderboardSet(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    data = openapi_client.models.game_center_detail_relationships_game_center_leaderboard_sets_data_inner.GameCenterDetail_relationships_gameCenterLeaderboardSets_data_inner(
                        type = 'gameCenterLeaderboardSets', 
                        id = '', ), ),
                localizations = openapi_client.models.game_center_leaderboard_set_relationships_localizations.GameCenterLeaderboardSet_relationships_localizations(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.game_center_leaderboard_set_image_relationships_game_center_leaderboard_set_localization_data.GameCenterLeaderboardSetImage_relationships_gameCenterLeaderboardSetLocalization_data(
                            type = 'gameCenterLeaderboardSetLocalizations', 
                            id = '', )
                        ], ),
                game_center_leaderboards = openapi_client.models.game_center_activity_relationships_leaderboards.GameCenterActivity_relationships_leaderboards(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.game_center_activity_relationships_leaderboards_data_inner.GameCenterActivity_relationships_leaderboards_data_inner(
                            type = 'gameCenterLeaderboards', 
                            id = '', )
                        ], ),
                releases = openapi_client.models.game_center_detail_relationships_leaderboard_set_releases.GameCenterDetail_relationships_leaderboardSetReleases(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), 
                    meta = openapi_client.models.paging_information.PagingInformation(
                        paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                            total = 56, 
                            limit = 56, 
                            next_cursor = '', ), ), 
                    data = [
                        openapi_client.models.game_center_detail_relationships_leaderboard_set_releases_data_inner.GameCenterDetail_relationships_leaderboardSetReleases_data_inner(
                            type = 'gameCenterLeaderboardSetReleases', 
                            id = '', )
                        ], )
            )
        else:
            return GameCenterLeaderboardSetRelationships(
        )
        """

    def testGameCenterLeaderboardSetRelationships(self):
        """Test GameCenterLeaderboardSetRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
