# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscription_promotional_offer_update_request_data_relationships import SubscriptionPromotionalOfferUpdateRequestDataRelationships

class TestSubscriptionPromotionalOfferUpdateRequestDataRelationships(unittest.TestCase):
    """SubscriptionPromotionalOfferUpdateRequestDataRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionPromotionalOfferUpdateRequestDataRelationships:
        """Test SubscriptionPromotionalOfferUpdateRequestDataRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionPromotionalOfferUpdateRequestDataRelationships`
        """
        model = SubscriptionPromotionalOfferUpdateRequestDataRelationships()
        if include_optional:
            return SubscriptionPromotionalOfferUpdateRequestDataRelationships(
                prices = openapi_client.models.subscription_promotional_offer_inline_create_relationships_prices.SubscriptionPromotionalOfferInlineCreate_relationships_prices(
                    data = [
                        openapi_client.models.subscription_promotional_offer_relationships_prices_data_inner.SubscriptionPromotionalOffer_relationships_prices_data_inner(
                            type = 'subscriptionPromotionalOfferPrices', 
                            id = '', )
                        ], )
            )
        else:
            return SubscriptionPromotionalOfferUpdateRequestDataRelationships(
        )
        """

    def testSubscriptionPromotionalOfferUpdateRequestDataRelationships(self):
        """Test SubscriptionPromotionalOfferUpdateRequestDataRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
