# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_clip_header_image_response import AppClipHeaderImageResponse

class TestAppClipHeaderImageResponse(unittest.TestCase):
    """AppClipHeaderImageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppClipHeaderImageResponse:
        """Test AppClipHeaderImageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppClipHeaderImageResponse`
        """
        model = AppClipHeaderImageResponse()
        if include_optional:
            return AppClipHeaderImageResponse(
                data = openapi_client.models.app_clip_header_image.AppClipHeaderImage(
                    type = 'appClipHeaderImages', 
                    id = '', 
                    attributes = openapi_client.models.app_clip_advanced_experience_image_attributes.AppClipAdvancedExperienceImage_attributes(
                        file_size = 56, 
                        file_name = '', 
                        source_file_checksum = '', 
                        image_asset = openapi_client.models.image_asset.ImageAsset(
                            template_url = '', 
                            width = 56, 
                            height = 56, ), 
                        upload_operations = [
                            openapi_client.models.upload_operation.UploadOperation(
                                method = '', 
                                url = '', 
                                length = 56, 
                                offset = 56, 
                                request_headers = [
                                    openapi_client.models.http_header.HttpHeader(
                                        name = '', 
                                        value = '', )
                                    ], )
                            ], 
                        asset_delivery_state = openapi_client.models.app_media_asset_state.AppMediaAssetState(
                            errors = [
                                openapi_client.models.app_media_state_error.AppMediaStateError(
                                    code = '', 
                                    description = '', )
                                ], 
                            warnings = [
                                openapi_client.models.app_media_state_error.AppMediaStateError(
                                    code = '', 
                                    description = '', )
                                ], 
                            state = 'AWAITING_UPLOAD', ), ), 
                    relationships = openapi_client.models.app_clip_header_image_relationships.AppClipHeaderImage_relationships(
                        app_clip_default_experience_localization = openapi_client.models.app_clip_header_image_relationships_app_clip_default_experience_localization.AppClipHeaderImage_relationships_appClipDefaultExperienceLocalization(
                            data = openapi_client.models.app_clip_default_experience_relationships_app_clip_default_experience_localizations_data_inner.AppClipDefaultExperience_relationships_appClipDefaultExperienceLocalizations_data_inner(
                                type = 'appClipDefaultExperienceLocalizations', 
                                id = '', ), ), ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                included = [
                    openapi_client.models.app_clip_default_experience_localization.AppClipDefaultExperienceLocalization(
                        type = 'appClipDefaultExperienceLocalizations', 
                        id = '', 
                        attributes = openapi_client.models.app_clip_default_experience_localization_attributes.AppClipDefaultExperienceLocalization_attributes(
                            locale = '', 
                            subtitle = '', ), 
                        relationships = openapi_client.models.app_clip_default_experience_localization_relationships.AppClipDefaultExperienceLocalization_relationships(
                            app_clip_default_experience = openapi_client.models.app_clip_app_store_review_detail_relationships_app_clip_default_experience.AppClipAppStoreReviewDetail_relationships_appClipDefaultExperience(
                                data = openapi_client.models.app_clip_app_store_review_detail_relationships_app_clip_default_experience_data.AppClipAppStoreReviewDetail_relationships_appClipDefaultExperience_data(
                                    type = 'appClipDefaultExperiences', 
                                    id = '', ), ), 
                            app_clip_header_image = openapi_client.models.app_clip_default_experience_localization_relationships_app_clip_header_image.AppClipDefaultExperienceLocalization_relationships_appClipHeaderImage(
                                links = openapi_client.models.relationship_links.RelationshipLinks(
                                    self = '', 
                                    related = '', ), ), ), 
                        links = openapi_client.models.resource_links.ResourceLinks(
                            self = '', ), )
                    ],
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', )
            )
        else:
            return AppClipHeaderImageResponse(
                data = openapi_client.models.app_clip_header_image.AppClipHeaderImage(
                    type = 'appClipHeaderImages', 
                    id = '', 
                    attributes = openapi_client.models.app_clip_advanced_experience_image_attributes.AppClipAdvancedExperienceImage_attributes(
                        file_size = 56, 
                        file_name = '', 
                        source_file_checksum = '', 
                        image_asset = openapi_client.models.image_asset.ImageAsset(
                            template_url = '', 
                            width = 56, 
                            height = 56, ), 
                        upload_operations = [
                            openapi_client.models.upload_operation.UploadOperation(
                                method = '', 
                                url = '', 
                                length = 56, 
                                offset = 56, 
                                request_headers = [
                                    openapi_client.models.http_header.HttpHeader(
                                        name = '', 
                                        value = '', )
                                    ], )
                            ], 
                        asset_delivery_state = openapi_client.models.app_media_asset_state.AppMediaAssetState(
                            errors = [
                                openapi_client.models.app_media_state_error.AppMediaStateError(
                                    code = '', 
                                    description = '', )
                                ], 
                            warnings = [
                                openapi_client.models.app_media_state_error.AppMediaStateError(
                                    code = '', 
                                    description = '', )
                                ], 
                            state = 'AWAITING_UPLOAD', ), ), 
                    relationships = openapi_client.models.app_clip_header_image_relationships.AppClipHeaderImage_relationships(
                        app_clip_default_experience_localization = openapi_client.models.app_clip_header_image_relationships_app_clip_default_experience_localization.AppClipHeaderImage_relationships_appClipDefaultExperienceLocalization(
                            data = openapi_client.models.app_clip_default_experience_relationships_app_clip_default_experience_localizations_data_inner.AppClipDefaultExperience_relationships_appClipDefaultExperienceLocalizations_data_inner(
                                type = 'appClipDefaultExperienceLocalizations', 
                                id = '', ), ), ), 
                    links = openapi_client.models.resource_links.ResourceLinks(
                        self = '', ), ),
                links = openapi_client.models.document_links.DocumentLinks(
                    self = '', ),
        )
        """

    def testAppClipHeaderImageResponse(self):
        """Test AppClipHeaderImageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
