# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scm_repository_relationships import ScmRepositoryRelationships

class TestScmRepositoryRelationships(unittest.TestCase):
    """ScmRepositoryRelationships unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScmRepositoryRelationships:
        """Test ScmRepositoryRelationships
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScmRepositoryRelationships`
        """
        model = ScmRepositoryRelationships()
        if include_optional:
            return ScmRepositoryRelationships(
                scm_provider = openapi_client.models.scm_repository_relationships_scm_provider.ScmRepository_relationships_scmProvider(
                    data = openapi_client.models.scm_repository_relationships_scm_provider_data.ScmRepository_relationships_scmProvider_data(
                        type = 'scmProviders', 
                        id = '', ), ),
                default_branch = openapi_client.models.ci_build_run_relationships_source_branch_or_tag.CiBuildRun_relationships_sourceBranchOrTag(
                    data = openapi_client.models.ci_build_run_relationships_source_branch_or_tag_data.CiBuildRun_relationships_sourceBranchOrTag_data(
                        type = 'scmGitReferences', 
                        id = '', ), ),
                git_references = openapi_client.models.analytics_report_instance_relationships_segments.AnalyticsReportInstance_relationships_segments(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), ),
                pull_requests = openapi_client.models.analytics_report_instance_relationships_segments.AnalyticsReportInstance_relationships_segments(
                    links = openapi_client.models.relationship_links.RelationshipLinks(
                        self = '', 
                        related = '', ), )
            )
        else:
            return ScmRepositoryRelationships(
        )
        """

    def testScmRepositoryRelationships(self):
        """Test ScmRepositoryRelationships"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
