# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscriptions_response_included_inner import SubscriptionsResponseIncludedInner

class TestSubscriptionsResponseIncludedInner(unittest.TestCase):
    """SubscriptionsResponseIncludedInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionsResponseIncludedInner:
        """Test SubscriptionsResponseIncludedInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionsResponseIncludedInner`
        """
        model = SubscriptionsResponseIncludedInner()
        if include_optional:
            return SubscriptionsResponseIncludedInner(
                type = 'subscriptionLocalizations',
                id = '',
                attributes = openapi_client.models.in_app_purchase_image_attributes.InAppPurchaseImage_attributes(
                    file_size = 56, 
                    file_name = '', 
                    source_file_checksum = '', 
                    asset_token = '', 
                    image_asset = openapi_client.models.image_asset.ImageAsset(
                        template_url = '', 
                        width = 56, 
                        height = 56, ), 
                    upload_operations = [
                        openapi_client.models.upload_operation.UploadOperation(
                            method = '', 
                            url = '', 
                            length = 56, 
                            offset = 56, 
                            request_headers = [
                                openapi_client.models.http_header.HttpHeader(
                                    name = '', 
                                    value = '', )
                                ], )
                        ], 
                    state = 'AWAITING_UPLOAD', ),
                relationships = openapi_client.models.subscription_app_store_review_screenshot_relationships.SubscriptionAppStoreReviewScreenshot_relationships(
                    subscription = openapi_client.models.promoted_purchase_relationships_subscription.PromotedPurchase_relationships_subscription(
                        data = openapi_client.models.promoted_purchase_relationships_subscription_data.PromotedPurchase_relationships_subscription_data(
                            type = 'subscriptions', 
                            id = '', ), ), ),
                links = openapi_client.models.resource_links.ResourceLinks(
                    self = '', )
            )
        else:
            return SubscriptionsResponseIncludedInner(
                type = 'subscriptionLocalizations',
                id = '',
        )
        """

    def testSubscriptionsResponseIncludedInner(self):
        """Test SubscriptionsResponseIncludedInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
