# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_matchmaking_app_requests_v1_metric_response_data_inner_data_points_values import GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues

class TestGameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues(unittest.TestCase):
    """GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues:
        """Test GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues`
        """
        model = GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues()
        if include_optional:
            return GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues(
                count = 56,
                average_seconds_in_queue = 1.337,
                p50_seconds_in_queue = 1.337,
                p95_seconds_in_queue = 1.337
            )
        else:
            return GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues(
        )
        """

    def testGameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues(self):
        """Test GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPointsValues"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
