# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_store_version_localization import AppStoreVersionLocalization

class TestAppStoreVersionLocalization(unittest.TestCase):
    """AppStoreVersionLocalization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppStoreVersionLocalization:
        """Test AppStoreVersionLocalization
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppStoreVersionLocalization`
        """
        model = AppStoreVersionLocalization()
        if include_optional:
            return AppStoreVersionLocalization(
                type = 'appStoreVersionLocalizations',
                id = '',
                attributes = openapi_client.models.app_store_version_localization_attributes.AppStoreVersionLocalization_attributes(
                    description = '', 
                    locale = '', 
                    keywords = '', 
                    marketing_url = '', 
                    promotional_text = '', 
                    support_url = '', 
                    whats_new = '', ),
                relationships = openapi_client.models.app_store_version_localization_relationships.AppStoreVersionLocalization_relationships(
                    app_store_version = openapi_client.models.app_clip_default_experience_create_request_data_relationships_release_with_app_store_version.AppClipDefaultExperienceCreateRequest_data_relationships_releaseWithAppStoreVersion(
                        data = openapi_client.models.alternative_distribution_package_create_request_data_relationships_app_store_version_data.AlternativeDistributionPackageCreateRequest_data_relationships_appStoreVersion_data(
                            type = 'appStoreVersions', 
                            id = '', ), ), 
                    app_screenshot_sets = openapi_client.models.app_custom_product_page_localization_relationships_app_screenshot_sets.AppCustomProductPageLocalization_relationships_appScreenshotSets(
                        links = openapi_client.models.relationship_links.RelationshipLinks(
                            self = '', 
                            related = '', ), 
                        meta = openapi_client.models.paging_information.PagingInformation(
                            paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                                total = 56, 
                                limit = 56, 
                                next_cursor = '', ), ), ), 
                    app_preview_sets = openapi_client.models.app_custom_product_page_localization_relationships_app_preview_sets.AppCustomProductPageLocalization_relationships_appPreviewSets(), ),
                links = openapi_client.models.resource_links.ResourceLinks(
                    self = '', )
            )
        else:
            return AppStoreVersionLocalization(
                type = 'appStoreVersionLocalizations',
                id = '',
        )
        """

    def testAppStoreVersionLocalization(self):
        """Test AppStoreVersionLocalization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
