# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.subscription_introductory_offers_api import SubscriptionIntroductoryOffersApi


class TestSubscriptionIntroductoryOffersApi(unittest.TestCase):
    """SubscriptionIntroductoryOffersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionIntroductoryOffersApi()

    def tearDown(self) -> None:
        pass

    def test_subscription_introductory_offers_create_instance(self) -> None:
        """Test case for subscription_introductory_offers_create_instance

        """
        pass

    def test_subscription_introductory_offers_delete_instance(self) -> None:
        """Test case for subscription_introductory_offers_delete_instance

        """
        pass

    def test_subscription_introductory_offers_update_instance(self) -> None:
        """Test case for subscription_introductory_offers_update_instance

        """
        pass


if __name__ == '__main__':
    unittest.main()
