# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subscription_create_request_data_attributes import SubscriptionCreateRequestDataAttributes

class TestSubscriptionCreateRequestDataAttributes(unittest.TestCase):
    """SubscriptionCreateRequestDataAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionCreateRequestDataAttributes:
        """Test SubscriptionCreateRequestDataAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionCreateRequestDataAttributes`
        """
        model = SubscriptionCreateRequestDataAttributes()
        if include_optional:
            return SubscriptionCreateRequestDataAttributes(
                name = '',
                product_id = '',
                family_sharable = True,
                subscription_period = 'ONE_WEEK',
                review_note = '',
                group_level = 56
            )
        else:
            return SubscriptionCreateRequestDataAttributes(
                name = '',
                product_id = '',
        )
        """

    def testSubscriptionCreateRequestDataAttributes(self):
        """Test SubscriptionCreateRequestDataAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
