# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ci_workflow_relationships_xcode_version import CiWorkflowRelationshipsXcodeVersion

class TestCiWorkflowRelationshipsXcodeVersion(unittest.TestCase):
    """CiWorkflowRelationshipsXcodeVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CiWorkflowRelationshipsXcodeVersion:
        """Test CiWorkflowRelationshipsXcodeVersion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CiWorkflowRelationshipsXcodeVersion`
        """
        model = CiWorkflowRelationshipsXcodeVersion()
        if include_optional:
            return CiWorkflowRelationshipsXcodeVersion(
                data = openapi_client.models.ci_mac_os_version_relationships_xcode_versions_data_inner.CiMacOsVersion_relationships_xcodeVersions_data_inner(
                    type = 'ciXcodeVersions', 
                    id = '', )
            )
        else:
            return CiWorkflowRelationshipsXcodeVersion(
        )
        """

    def testCiWorkflowRelationshipsXcodeVersion(self):
        """Test CiWorkflowRelationshipsXcodeVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
