# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ci_products_api import CiProductsApi


class TestCiProductsApi(unittest.TestCase):
    """CiProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CiProductsApi()

    def tearDown(self) -> None:
        pass

    def test_ci_products_additional_repositories_get_to_many_related(self) -> None:
        """Test case for ci_products_additional_repositories_get_to_many_related

        """
        pass

    def test_ci_products_additional_repositories_get_to_many_relationship(self) -> None:
        """Test case for ci_products_additional_repositories_get_to_many_relationship

        """
        pass

    def test_ci_products_app_get_to_one_related(self) -> None:
        """Test case for ci_products_app_get_to_one_related

        """
        pass

    def test_ci_products_app_get_to_one_relationship(self) -> None:
        """Test case for ci_products_app_get_to_one_relationship

        """
        pass

    def test_ci_products_build_runs_get_to_many_related(self) -> None:
        """Test case for ci_products_build_runs_get_to_many_related

        """
        pass

    def test_ci_products_build_runs_get_to_many_relationship(self) -> None:
        """Test case for ci_products_build_runs_get_to_many_relationship

        """
        pass

    def test_ci_products_delete_instance(self) -> None:
        """Test case for ci_products_delete_instance

        """
        pass

    def test_ci_products_get_collection(self) -> None:
        """Test case for ci_products_get_collection

        """
        pass

    def test_ci_products_get_instance(self) -> None:
        """Test case for ci_products_get_instance

        """
        pass

    def test_ci_products_primary_repositories_get_to_many_related(self) -> None:
        """Test case for ci_products_primary_repositories_get_to_many_related

        """
        pass

    def test_ci_products_primary_repositories_get_to_many_relationship(self) -> None:
        """Test case for ci_products_primary_repositories_get_to_many_relationship

        """
        pass

    def test_ci_products_workflows_get_to_many_related(self) -> None:
        """Test case for ci_products_workflows_get_to_many_related

        """
        pass

    def test_ci_products_workflows_get_to_many_relationship(self) -> None:
        """Test case for ci_products_workflows_get_to_many_relationship

        """
        pass


if __name__ == '__main__':
    unittest.main()
