# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.game_center_activity_version_relationships_localizations import GameCenterActivityVersionRelationshipsLocalizations

class TestGameCenterActivityVersionRelationshipsLocalizations(unittest.TestCase):
    """GameCenterActivityVersionRelationshipsLocalizations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameCenterActivityVersionRelationshipsLocalizations:
        """Test GameCenterActivityVersionRelationshipsLocalizations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameCenterActivityVersionRelationshipsLocalizations`
        """
        model = GameCenterActivityVersionRelationshipsLocalizations()
        if include_optional:
            return GameCenterActivityVersionRelationshipsLocalizations(
                links = openapi_client.models.relationship_links.RelationshipLinks(
                    self = '', 
                    related = '', ),
                meta = openapi_client.models.paging_information.PagingInformation(
                    paging = openapi_client.models.paging_information_paging.PagingInformation_paging(
                        total = 56, 
                        limit = 56, 
                        next_cursor = '', ), ),
                data = [
                    openapi_client.models.game_center_activity_image_create_request_data_relationships_localization_data.GameCenterActivityImageCreateRequest_data_relationships_localization_data(
                        type = 'gameCenterActivityLocalizations', 
                        id = '', )
                    ]
            )
        else:
            return GameCenterActivityVersionRelationshipsLocalizations(
        )
        """

    def testGameCenterActivityVersionRelationshipsLocalizations(self):
        """Test GameCenterActivityVersionRelationshipsLocalizations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
