# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BuildAudienceType(str, Enum):
    """
    BuildAudienceType
    """

    """
    allowed enum values
    """
    INTERNAL_ONLY = 'INTERNAL_ONLY'
    APP_STORE_ELIGIBLE = 'APP_STORE_ELIGIBLE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BuildAudienceType from a JSON string"""
        return cls(json.loads(json_str))


