# coding: utf-8

"""
    App Store Connect API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from openapi_client.models.build_beta_detail_build_linkage_response import BuildBetaDetailBuildLinkageResponse
from openapi_client.models.build_beta_detail_response import BuildBetaDetailResponse
from openapi_client.models.build_beta_detail_update_request import BuildBetaDetailUpdateRequest
from openapi_client.models.build_beta_details_response import BuildBetaDetailsResponse
from openapi_client.models.build_response import BuildResponse

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class BuildBetaDetailsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def build_beta_details_build_get_to_one_related(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        fields_pre_release_versions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type preReleaseVersions")] = None,
        fields_beta_testers: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaTesters")] = None,
        fields_beta_groups: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaGroups")] = None,
        fields_beta_build_localizations: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaBuildLocalizations")] = None,
        fields_app_encryption_declarations: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type appEncryptionDeclarations")] = None,
        fields_beta_app_review_submissions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaAppReviewSubmissions")] = None,
        fields_apps: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type apps")] = None,
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_app_store_versions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type appStoreVersions")] = None,
        fields_build_icons: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildIcons")] = None,
        fields_build_bundles: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBundles")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        limit_individual_testers: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related individualTesters returned (when they are included)")] = None,
        limit_beta_groups: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related betaGroups returned (when they are included)")] = None,
        limit_beta_build_localizations: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related betaBuildLocalizations returned (when they are included)")] = None,
        limit_icons: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related icons returned (when they are included)")] = None,
        limit_build_bundles: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related buildBundles returned (when they are included)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BuildResponse:
        """build_beta_details_build_get_to_one_related


        :param id: the id of the requested resource (required)
        :type id: str
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param fields_pre_release_versions: the fields to include for returned resources of type preReleaseVersions
        :type fields_pre_release_versions: List[str]
        :param fields_beta_testers: the fields to include for returned resources of type betaTesters
        :type fields_beta_testers: List[str]
        :param fields_beta_groups: the fields to include for returned resources of type betaGroups
        :type fields_beta_groups: List[str]
        :param fields_beta_build_localizations: the fields to include for returned resources of type betaBuildLocalizations
        :type fields_beta_build_localizations: List[str]
        :param fields_app_encryption_declarations: the fields to include for returned resources of type appEncryptionDeclarations
        :type fields_app_encryption_declarations: List[str]
        :param fields_beta_app_review_submissions: the fields to include for returned resources of type betaAppReviewSubmissions
        :type fields_beta_app_review_submissions: List[str]
        :param fields_apps: the fields to include for returned resources of type apps
        :type fields_apps: List[str]
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_app_store_versions: the fields to include for returned resources of type appStoreVersions
        :type fields_app_store_versions: List[str]
        :param fields_build_icons: the fields to include for returned resources of type buildIcons
        :type fields_build_icons: List[str]
        :param fields_build_bundles: the fields to include for returned resources of type buildBundles
        :type fields_build_bundles: List[str]
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param limit_individual_testers: maximum number of related individualTesters returned (when they are included)
        :type limit_individual_testers: int
        :param limit_beta_groups: maximum number of related betaGroups returned (when they are included)
        :type limit_beta_groups: int
        :param limit_beta_build_localizations: maximum number of related betaBuildLocalizations returned (when they are included)
        :type limit_beta_build_localizations: int
        :param limit_icons: maximum number of related icons returned (when they are included)
        :type limit_icons: int
        :param limit_build_bundles: maximum number of related buildBundles returned (when they are included)
        :type limit_build_bundles: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_build_get_to_one_related_serialize(
            id=id,
            fields_builds=fields_builds,
            fields_pre_release_versions=fields_pre_release_versions,
            fields_beta_testers=fields_beta_testers,
            fields_beta_groups=fields_beta_groups,
            fields_beta_build_localizations=fields_beta_build_localizations,
            fields_app_encryption_declarations=fields_app_encryption_declarations,
            fields_beta_app_review_submissions=fields_beta_app_review_submissions,
            fields_apps=fields_apps,
            fields_build_beta_details=fields_build_beta_details,
            fields_app_store_versions=fields_app_store_versions,
            fields_build_icons=fields_build_icons,
            fields_build_bundles=fields_build_bundles,
            include=include,
            limit_individual_testers=limit_individual_testers,
            limit_beta_groups=limit_beta_groups,
            limit_beta_build_localizations=limit_beta_build_localizations,
            limit_icons=limit_icons,
            limit_build_bundles=limit_build_bundles,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def build_beta_details_build_get_to_one_related_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        fields_pre_release_versions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type preReleaseVersions")] = None,
        fields_beta_testers: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaTesters")] = None,
        fields_beta_groups: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaGroups")] = None,
        fields_beta_build_localizations: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaBuildLocalizations")] = None,
        fields_app_encryption_declarations: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type appEncryptionDeclarations")] = None,
        fields_beta_app_review_submissions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaAppReviewSubmissions")] = None,
        fields_apps: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type apps")] = None,
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_app_store_versions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type appStoreVersions")] = None,
        fields_build_icons: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildIcons")] = None,
        fields_build_bundles: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBundles")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        limit_individual_testers: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related individualTesters returned (when they are included)")] = None,
        limit_beta_groups: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related betaGroups returned (when they are included)")] = None,
        limit_beta_build_localizations: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related betaBuildLocalizations returned (when they are included)")] = None,
        limit_icons: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related icons returned (when they are included)")] = None,
        limit_build_bundles: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related buildBundles returned (when they are included)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BuildResponse]:
        """build_beta_details_build_get_to_one_related


        :param id: the id of the requested resource (required)
        :type id: str
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param fields_pre_release_versions: the fields to include for returned resources of type preReleaseVersions
        :type fields_pre_release_versions: List[str]
        :param fields_beta_testers: the fields to include for returned resources of type betaTesters
        :type fields_beta_testers: List[str]
        :param fields_beta_groups: the fields to include for returned resources of type betaGroups
        :type fields_beta_groups: List[str]
        :param fields_beta_build_localizations: the fields to include for returned resources of type betaBuildLocalizations
        :type fields_beta_build_localizations: List[str]
        :param fields_app_encryption_declarations: the fields to include for returned resources of type appEncryptionDeclarations
        :type fields_app_encryption_declarations: List[str]
        :param fields_beta_app_review_submissions: the fields to include for returned resources of type betaAppReviewSubmissions
        :type fields_beta_app_review_submissions: List[str]
        :param fields_apps: the fields to include for returned resources of type apps
        :type fields_apps: List[str]
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_app_store_versions: the fields to include for returned resources of type appStoreVersions
        :type fields_app_store_versions: List[str]
        :param fields_build_icons: the fields to include for returned resources of type buildIcons
        :type fields_build_icons: List[str]
        :param fields_build_bundles: the fields to include for returned resources of type buildBundles
        :type fields_build_bundles: List[str]
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param limit_individual_testers: maximum number of related individualTesters returned (when they are included)
        :type limit_individual_testers: int
        :param limit_beta_groups: maximum number of related betaGroups returned (when they are included)
        :type limit_beta_groups: int
        :param limit_beta_build_localizations: maximum number of related betaBuildLocalizations returned (when they are included)
        :type limit_beta_build_localizations: int
        :param limit_icons: maximum number of related icons returned (when they are included)
        :type limit_icons: int
        :param limit_build_bundles: maximum number of related buildBundles returned (when they are included)
        :type limit_build_bundles: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_build_get_to_one_related_serialize(
            id=id,
            fields_builds=fields_builds,
            fields_pre_release_versions=fields_pre_release_versions,
            fields_beta_testers=fields_beta_testers,
            fields_beta_groups=fields_beta_groups,
            fields_beta_build_localizations=fields_beta_build_localizations,
            fields_app_encryption_declarations=fields_app_encryption_declarations,
            fields_beta_app_review_submissions=fields_beta_app_review_submissions,
            fields_apps=fields_apps,
            fields_build_beta_details=fields_build_beta_details,
            fields_app_store_versions=fields_app_store_versions,
            fields_build_icons=fields_build_icons,
            fields_build_bundles=fields_build_bundles,
            include=include,
            limit_individual_testers=limit_individual_testers,
            limit_beta_groups=limit_beta_groups,
            limit_beta_build_localizations=limit_beta_build_localizations,
            limit_icons=limit_icons,
            limit_build_bundles=limit_build_bundles,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def build_beta_details_build_get_to_one_related_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        fields_pre_release_versions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type preReleaseVersions")] = None,
        fields_beta_testers: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaTesters")] = None,
        fields_beta_groups: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaGroups")] = None,
        fields_beta_build_localizations: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaBuildLocalizations")] = None,
        fields_app_encryption_declarations: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type appEncryptionDeclarations")] = None,
        fields_beta_app_review_submissions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type betaAppReviewSubmissions")] = None,
        fields_apps: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type apps")] = None,
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_app_store_versions: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type appStoreVersions")] = None,
        fields_build_icons: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildIcons")] = None,
        fields_build_bundles: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBundles")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        limit_individual_testers: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related individualTesters returned (when they are included)")] = None,
        limit_beta_groups: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related betaGroups returned (when they are included)")] = None,
        limit_beta_build_localizations: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related betaBuildLocalizations returned (when they are included)")] = None,
        limit_icons: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related icons returned (when they are included)")] = None,
        limit_build_bundles: Annotated[Optional[Annotated[int, Field(le=50, strict=True)]], Field(description="maximum number of related buildBundles returned (when they are included)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """build_beta_details_build_get_to_one_related


        :param id: the id of the requested resource (required)
        :type id: str
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param fields_pre_release_versions: the fields to include for returned resources of type preReleaseVersions
        :type fields_pre_release_versions: List[str]
        :param fields_beta_testers: the fields to include for returned resources of type betaTesters
        :type fields_beta_testers: List[str]
        :param fields_beta_groups: the fields to include for returned resources of type betaGroups
        :type fields_beta_groups: List[str]
        :param fields_beta_build_localizations: the fields to include for returned resources of type betaBuildLocalizations
        :type fields_beta_build_localizations: List[str]
        :param fields_app_encryption_declarations: the fields to include for returned resources of type appEncryptionDeclarations
        :type fields_app_encryption_declarations: List[str]
        :param fields_beta_app_review_submissions: the fields to include for returned resources of type betaAppReviewSubmissions
        :type fields_beta_app_review_submissions: List[str]
        :param fields_apps: the fields to include for returned resources of type apps
        :type fields_apps: List[str]
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_app_store_versions: the fields to include for returned resources of type appStoreVersions
        :type fields_app_store_versions: List[str]
        :param fields_build_icons: the fields to include for returned resources of type buildIcons
        :type fields_build_icons: List[str]
        :param fields_build_bundles: the fields to include for returned resources of type buildBundles
        :type fields_build_bundles: List[str]
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param limit_individual_testers: maximum number of related individualTesters returned (when they are included)
        :type limit_individual_testers: int
        :param limit_beta_groups: maximum number of related betaGroups returned (when they are included)
        :type limit_beta_groups: int
        :param limit_beta_build_localizations: maximum number of related betaBuildLocalizations returned (when they are included)
        :type limit_beta_build_localizations: int
        :param limit_icons: maximum number of related icons returned (when they are included)
        :type limit_icons: int
        :param limit_build_bundles: maximum number of related buildBundles returned (when they are included)
        :type limit_build_bundles: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_build_get_to_one_related_serialize(
            id=id,
            fields_builds=fields_builds,
            fields_pre_release_versions=fields_pre_release_versions,
            fields_beta_testers=fields_beta_testers,
            fields_beta_groups=fields_beta_groups,
            fields_beta_build_localizations=fields_beta_build_localizations,
            fields_app_encryption_declarations=fields_app_encryption_declarations,
            fields_beta_app_review_submissions=fields_beta_app_review_submissions,
            fields_apps=fields_apps,
            fields_build_beta_details=fields_build_beta_details,
            fields_app_store_versions=fields_app_store_versions,
            fields_build_icons=fields_build_icons,
            fields_build_bundles=fields_build_bundles,
            include=include,
            limit_individual_testers=limit_individual_testers,
            limit_beta_groups=limit_beta_groups,
            limit_beta_build_localizations=limit_beta_build_localizations,
            limit_icons=limit_icons,
            limit_build_bundles=limit_build_bundles,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _build_beta_details_build_get_to_one_related_serialize(
        self,
        id,
        fields_builds,
        fields_pre_release_versions,
        fields_beta_testers,
        fields_beta_groups,
        fields_beta_build_localizations,
        fields_app_encryption_declarations,
        fields_beta_app_review_submissions,
        fields_apps,
        fields_build_beta_details,
        fields_app_store_versions,
        fields_build_icons,
        fields_build_bundles,
        include,
        limit_individual_testers,
        limit_beta_groups,
        limit_beta_build_localizations,
        limit_icons,
        limit_build_bundles,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'fields[builds]': 'csv',
            'fields[preReleaseVersions]': 'csv',
            'fields[betaTesters]': 'csv',
            'fields[betaGroups]': 'csv',
            'fields[betaBuildLocalizations]': 'csv',
            'fields[appEncryptionDeclarations]': 'csv',
            'fields[betaAppReviewSubmissions]': 'csv',
            'fields[apps]': 'csv',
            'fields[buildBetaDetails]': 'csv',
            'fields[appStoreVersions]': 'csv',
            'fields[buildIcons]': 'csv',
            'fields[buildBundles]': 'csv',
            'include': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        if fields_builds is not None:
            
            _query_params.append(('fields[builds]', fields_builds))
            
        if fields_pre_release_versions is not None:
            
            _query_params.append(('fields[preReleaseVersions]', fields_pre_release_versions))
            
        if fields_beta_testers is not None:
            
            _query_params.append(('fields[betaTesters]', fields_beta_testers))
            
        if fields_beta_groups is not None:
            
            _query_params.append(('fields[betaGroups]', fields_beta_groups))
            
        if fields_beta_build_localizations is not None:
            
            _query_params.append(('fields[betaBuildLocalizations]', fields_beta_build_localizations))
            
        if fields_app_encryption_declarations is not None:
            
            _query_params.append(('fields[appEncryptionDeclarations]', fields_app_encryption_declarations))
            
        if fields_beta_app_review_submissions is not None:
            
            _query_params.append(('fields[betaAppReviewSubmissions]', fields_beta_app_review_submissions))
            
        if fields_apps is not None:
            
            _query_params.append(('fields[apps]', fields_apps))
            
        if fields_build_beta_details is not None:
            
            _query_params.append(('fields[buildBetaDetails]', fields_build_beta_details))
            
        if fields_app_store_versions is not None:
            
            _query_params.append(('fields[appStoreVersions]', fields_app_store_versions))
            
        if fields_build_icons is not None:
            
            _query_params.append(('fields[buildIcons]', fields_build_icons))
            
        if fields_build_bundles is not None:
            
            _query_params.append(('fields[buildBundles]', fields_build_bundles))
            
        if include is not None:
            
            _query_params.append(('include', include))
            
        if limit_individual_testers is not None:
            
            _query_params.append(('limit[individualTesters]', limit_individual_testers))
            
        if limit_beta_groups is not None:
            
            _query_params.append(('limit[betaGroups]', limit_beta_groups))
            
        if limit_beta_build_localizations is not None:
            
            _query_params.append(('limit[betaBuildLocalizations]', limit_beta_build_localizations))
            
        if limit_icons is not None:
            
            _query_params.append(('limit[icons]', limit_icons))
            
        if limit_build_bundles is not None:
            
            _query_params.append(('limit[buildBundles]', limit_build_bundles))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'itc-bearer-token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/buildBetaDetails/{id}/build',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def build_beta_details_build_get_to_one_relationship(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BuildBetaDetailBuildLinkageResponse:
        """build_beta_details_build_get_to_one_relationship


        :param id: the id of the requested resource (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_build_get_to_one_relationship_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildBetaDetailBuildLinkageResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def build_beta_details_build_get_to_one_relationship_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BuildBetaDetailBuildLinkageResponse]:
        """build_beta_details_build_get_to_one_relationship


        :param id: the id of the requested resource (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_build_get_to_one_relationship_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildBetaDetailBuildLinkageResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def build_beta_details_build_get_to_one_relationship_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """build_beta_details_build_get_to_one_relationship


        :param id: the id of the requested resource (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_build_get_to_one_relationship_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildBetaDetailBuildLinkageResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _build_beta_details_build_get_to_one_relationship_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'itc-bearer-token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/buildBetaDetails/{id}/relationships/build',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def build_beta_details_get_collection(
        self,
        filter_build: Annotated[Optional[List[StrictStr]], Field(description="filter by id(s) of related 'build'")] = None,
        filter_id: Annotated[Optional[List[StrictStr]], Field(description="filter by id(s)")] = None,
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=200, strict=True)]], Field(description="maximum resources per page")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BuildBetaDetailsResponse:
        """build_beta_details_get_collection


        :param filter_build: filter by id(s) of related 'build'
        :type filter_build: List[str]
        :param filter_id: filter by id(s)
        :type filter_id: List[str]
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param limit: maximum resources per page
        :type limit: int
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_get_collection_serialize(
            filter_build=filter_build,
            filter_id=filter_id,
            fields_build_beta_details=fields_build_beta_details,
            fields_builds=fields_builds,
            limit=limit,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '200': "BuildBetaDetailsResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def build_beta_details_get_collection_with_http_info(
        self,
        filter_build: Annotated[Optional[List[StrictStr]], Field(description="filter by id(s) of related 'build'")] = None,
        filter_id: Annotated[Optional[List[StrictStr]], Field(description="filter by id(s)")] = None,
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=200, strict=True)]], Field(description="maximum resources per page")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BuildBetaDetailsResponse]:
        """build_beta_details_get_collection


        :param filter_build: filter by id(s) of related 'build'
        :type filter_build: List[str]
        :param filter_id: filter by id(s)
        :type filter_id: List[str]
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param limit: maximum resources per page
        :type limit: int
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_get_collection_serialize(
            filter_build=filter_build,
            filter_id=filter_id,
            fields_build_beta_details=fields_build_beta_details,
            fields_builds=fields_builds,
            limit=limit,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '200': "BuildBetaDetailsResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def build_beta_details_get_collection_without_preload_content(
        self,
        filter_build: Annotated[Optional[List[StrictStr]], Field(description="filter by id(s) of related 'build'")] = None,
        filter_id: Annotated[Optional[List[StrictStr]], Field(description="filter by id(s)")] = None,
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=200, strict=True)]], Field(description="maximum resources per page")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """build_beta_details_get_collection


        :param filter_build: filter by id(s) of related 'build'
        :type filter_build: List[str]
        :param filter_id: filter by id(s)
        :type filter_id: List[str]
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param limit: maximum resources per page
        :type limit: int
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_get_collection_serialize(
            filter_build=filter_build,
            filter_id=filter_id,
            fields_build_beta_details=fields_build_beta_details,
            fields_builds=fields_builds,
            limit=limit,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '200': "BuildBetaDetailsResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _build_beta_details_get_collection_serialize(
        self,
        filter_build,
        filter_id,
        fields_build_beta_details,
        fields_builds,
        limit,
        include,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'filter[build]': 'csv',
            'filter[id]': 'csv',
            'fields[buildBetaDetails]': 'csv',
            'fields[builds]': 'csv',
            'include': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if filter_build is not None:
            
            _query_params.append(('filter[build]', filter_build))
            
        if filter_id is not None:
            
            _query_params.append(('filter[id]', filter_id))
            
        if fields_build_beta_details is not None:
            
            _query_params.append(('fields[buildBetaDetails]', fields_build_beta_details))
            
        if fields_builds is not None:
            
            _query_params.append(('fields[builds]', fields_builds))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if include is not None:
            
            _query_params.append(('include', include))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'itc-bearer-token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/buildBetaDetails',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def build_beta_details_get_instance(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BuildBetaDetailResponse:
        """build_beta_details_get_instance


        :param id: the id of the requested resource (required)
        :type id: str
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_get_instance_serialize(
            id=id,
            fields_build_beta_details=fields_build_beta_details,
            fields_builds=fields_builds,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildBetaDetailResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def build_beta_details_get_instance_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BuildBetaDetailResponse]:
        """build_beta_details_get_instance


        :param id: the id of the requested resource (required)
        :type id: str
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_get_instance_serialize(
            id=id,
            fields_build_beta_details=fields_build_beta_details,
            fields_builds=fields_builds,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildBetaDetailResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def build_beta_details_get_instance_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        fields_build_beta_details: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type buildBetaDetails")] = None,
        fields_builds: Annotated[Optional[List[StrictStr]], Field(description="the fields to include for returned resources of type builds")] = None,
        include: Annotated[Optional[List[StrictStr]], Field(description="comma-separated list of relationships to include")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """build_beta_details_get_instance


        :param id: the id of the requested resource (required)
        :type id: str
        :param fields_build_beta_details: the fields to include for returned resources of type buildBetaDetails
        :type fields_build_beta_details: List[str]
        :param fields_builds: the fields to include for returned resources of type builds
        :type fields_builds: List[str]
        :param include: comma-separated list of relationships to include
        :type include: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_get_instance_serialize(
            id=id,
            fields_build_beta_details=fields_build_beta_details,
            fields_builds=fields_builds,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '200': "BuildBetaDetailResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _build_beta_details_get_instance_serialize(
        self,
        id,
        fields_build_beta_details,
        fields_builds,
        include,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'fields[buildBetaDetails]': 'csv',
            'fields[builds]': 'csv',
            'include': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        if fields_build_beta_details is not None:
            
            _query_params.append(('fields[buildBetaDetails]', fields_build_beta_details))
            
        if fields_builds is not None:
            
            _query_params.append(('fields[builds]', fields_builds))
            
        if include is not None:
            
            _query_params.append(('include', include))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'itc-bearer-token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/buildBetaDetails/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def build_beta_details_update_instance(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        build_beta_detail_update_request: Annotated[BuildBetaDetailUpdateRequest, Field(description="BuildBetaDetail representation")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BuildBetaDetailResponse:
        """build_beta_details_update_instance


        :param id: the id of the requested resource (required)
        :type id: str
        :param build_beta_detail_update_request: BuildBetaDetail representation (required)
        :type build_beta_detail_update_request: BuildBetaDetailUpdateRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_update_instance_serialize(
            id=id,
            build_beta_detail_update_request=build_beta_detail_update_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '422': "ErrorResponse",
            '200': "BuildBetaDetailResponse",
            '409': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def build_beta_details_update_instance_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        build_beta_detail_update_request: Annotated[BuildBetaDetailUpdateRequest, Field(description="BuildBetaDetail representation")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BuildBetaDetailResponse]:
        """build_beta_details_update_instance


        :param id: the id of the requested resource (required)
        :type id: str
        :param build_beta_detail_update_request: BuildBetaDetail representation (required)
        :type build_beta_detail_update_request: BuildBetaDetailUpdateRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_update_instance_serialize(
            id=id,
            build_beta_detail_update_request=build_beta_detail_update_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '422': "ErrorResponse",
            '200': "BuildBetaDetailResponse",
            '409': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def build_beta_details_update_instance_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="the id of the requested resource")],
        build_beta_detail_update_request: Annotated[BuildBetaDetailUpdateRequest, Field(description="BuildBetaDetail representation")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """build_beta_details_update_instance


        :param id: the id of the requested resource (required)
        :type id: str
        :param build_beta_detail_update_request: BuildBetaDetail representation (required)
        :type build_beta_detail_update_request: BuildBetaDetailUpdateRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._build_beta_details_update_instance_serialize(
            id=id,
            build_beta_detail_update_request=build_beta_detail_update_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '422': "ErrorResponse",
            '200': "BuildBetaDetailResponse",
            '409': "ErrorResponse",
            '429': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _build_beta_details_update_instance_serialize(
        self,
        id,
        build_beta_detail_update_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if build_beta_detail_update_request is not None:
            _body_params = build_beta_detail_update_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'itc-bearer-token'
        ]

        return self.api_client.param_serialize(
            method='PATCH',
            resource_path='/v1/buildBetaDetails/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


